CC=distcc
#C_ARGS= -gstabs+ -Wall -D_cplusplus -D__INNER_DEBUG__PACKAGE_
C_ARGS= -g -Wall -D_cplusplus -D__INNER_DEBUG__PACKAGE_
SHARED = 

DEV_PATH=/home/jwf/work

MYSQL_INC=-I/usr/local/mysql/include/
MYSQL_LIB=/usr/local/mysql/lib/libmysqlclient_r.a

PROTOC_INC=-I/usr/local/protobuf/include/
PROTOC_LIB=/usr/local/lib/libprotobuf.a  /usr/local/lib/libtcmalloc_minimal.a

BASE_PATH=$(DEV_PATH)/frame/base
BASE_INC=-I$(BASE_PATH)/
BASE_LIB=$(BASE_PATH)/base.a

NAVMESH_PATH=$(DEV_PATH)/frame/navmesh
NAVMESH_INC=-I$(NAVMESH_PATH)/
NAVMESH_LIB=$(NAVMESH_PATH)/navmesh.a

ROLE_PATH=$(DEV_PATH)/frame/player_role
ROLE_INC=-I$(ROLE_PATH)/
ROLE_LIB=$(ROLE_PATH)/player_role.a

AMTSVR_PATH=$(DEV_PATH)/amtsvr
AMTSVR_INC=-I$(AMTSVR_PATH)/

PB_PATH=$(DEV_PATH)/frame/pb
PB_INC=-I$(PB_PATH)/client/ -I$(PB_PATH)/data/ -I$(PB_PATH)/server/ -I$(PB_PATH)/config/ -I$(PB_PATH)/inner/
PB_LIB=$(PB_PATH)/client/pb_client.a $(PB_PATH)/data/pb_data.a $(PB_PATH)/server/pb_server.a $(PB_PATH)/config/pb_config.a $(PB_PATH)/inner/pb_inner.a

CONFIG_PATH=$(DEV_PATH)/frame/config
CONFIG_INC=-I$(CONFIG_PATH)/
CONFIG_LIB=$(CONFIG_PATH)/config.a

SCENE_PATH=$(DEV_PATH)/frame/scene
SCENE_INC=-I$(SCENE_PATH)/
SCENE_LIB=$(SCENE_PATH)/scene.a

CENTER_MAIL_PATH=$(DEV_PATH)/frame/center/mail
CENTER_MAIL_INC=-I$(CENTER_MAIL_PATH)/
CENTER_MAIL_LIB=$(CENTER_MAIL_PATH)/center_mail.a

CENTER_CACHE_PATH=$(DEV_PATH)/frame/center/cache
CENTER_CACHE_INC=-I$(CENTER_CACHE_PATH)/
CENTER_CACHE_LIB=$(CENTER_CACHE_PATH)/center_cache.a

CENTER_CHAT_PATH=$(DEV_PATH)/frame/center/chat
CENTER_CHAT_INC=-I$(CENTER_CHAT_PATH)/
CENTER_CHAT_LIB=$(CENTER_CHAT_PATH)/center_chat.a

CENTER_FRIENDS_PATH=$(DEV_PATH)/frame/center/friends
CENTER_FRIENDS_INC=-I$(CENTER_FRIENDS_PATH)/
CENTER_FRIENDS_LIB=$(CENTER_FRIENDS_PATH)/center_friends.a

CENTER_BOSS_PATH=$(DEV_PATH)/frame/center/boss
CENTER_BOSS_INC=-I$(CENTER_BOSS_PATH)/
CENTER_BOSS_LIB=$(CENTER_BOSS_PATH)/center_boss.a

CENTER_RANK_PATH=$(DEV_PATH)/frame/center/rank
CENTER_RANK_INC=-I$(CENTER_RANK_PATH)/
CENTER_RANK_LIB=$(CENTER_RANK_PATH)/center_rank.a

CENTER_TEAM_PATH=$(DEV_PATH)/frame/center/team
CENTER_TEAM_INC=-I$(CENTER_TEAM_PATH)/
CENTER_TEAM_LIB=$(CENTER_TEAM_PATH)/center_team.a

CENTER_RAID_PATH=$(DEV_PATH)/frame/center/raid
CENTER_RAID_INC=-I$(CENTER_RAID_PATH)/
CENTER_RAID_LIB=$(CENTER_RAID_PATH)/center_raid.a

CENTER_FAMILY_PATH=$(DEV_PATH)/frame/center/family
CENTER_FAMILY_INC=-I$(CENTER_FAMILY_PATH)/
CENTER_FAMILY_LIB=$(CENTER_FAMILY_PATH)/center_family.a

CENTER_CITY_PATH=$(DEV_PATH)/frame/center/city
CENTER_CITY_INC=-I$(CENTER_CITY_PATH)/
CENTER_CITY_LIB=$(CENTER_CITY_PATH)/center_city.a

CENTER_CYCLE_PATH=$(DEV_PATH)/frame/center/cycle
CENTER_CYCLE_INC=-I$(CENTER_CYCLE_PATH)/
CENTER_CYCLE_LIB=$(CENTER_CYCLE_PATH)/center_cycle.a

CENTER_EXPLORE_PATH=$(DEV_PATH)/frame/center/explore
CENTER_EXPLORE_INC=-I$(CENTER_EXPLORE_PATH)/
CENTER_EXPLORE_LIB=$(CENTER_EXPLORE_PATH)/center_explore.a

CENTER_LINK_LUA_PATH=$(DEV_PATH)/frame/script/link
CENTER_LINK_LUA_INC=-I$(CENTER_LINK_LUA_PATH)/
CENTER_LINK_LUA_LIB=$(CENTER_LINK_LUA_PATH)/center_link_lua.a

CENTER_ARENA_PATH=$(DEV_PATH)/frame/center/arena
CENTER_ARENA_INC=-I$(CENTER_ARENA_PATH)/
CENTER_ARENA_LIB=$(CENTER_ARENA_PATH)/center_arena.a

CENTER_MATE_PATH=$(DEV_PATH)/frame/center/mate
CENTER_MATE_INC=-I$(CENTER_MATE_PATH)/
CENTER_MATE_LIB=$(CENTER_MATE_PATH)/center_mate.a

CENTER_POLL_ACTIVITY_PATH=$(DEV_PATH)/frame/center/poll_activity
CENTER_POLL_ACTIVITY_INC=-I$(CENTER_POLL_ACTIVITY_PATH)/
CENTER_POLL_ACTIVITY_LIB=$(CENTER_POLL_ACTIVITY_PATH)/poll_activity.a

CENTER_RANDNPC_PATH=$(DEV_PATH)/frame/center/randnpc
CENTER_RANDNPC_INC=-I$(CENTER_RANDNPC_PATH)/
CENTER_RANDNPC_LIB=$(CENTER_RANDNPC_PATH)/center_randnpc.a

CENTER_DEVIL_PATH=$(DEV_PATH)/frame/center/devil
CENTER_DEVIL_INC=-I$(CENTER_DEVIL_PATH)/
CENTER_DEVIL_LIB=$(CENTER_DEVIL_PATH)/center_devil.a

CENTER_ILLEGAL_WORD_PATH=$(DEV_PATH)/frame/center/illegal_word
CENTER_ILLEGAL_WORD_INC=-I$(CENTER_ILLEGAL_WORD_PATH)/
CENTER_ILLEGAL_WORD_LIB=$(CENTER_ILLEGAL_WORD_PATH)/center_illegal_word.a

CENTER_NOTICE_PATH=$(DEV_PATH)/frame/center/notice
CENTER_NOTICE_INC=-I$(CENTER_NOTICE_PATH)/
CENTER_NOTICE_LIB=$(CENTER_NOTICE_PATH)/center_notice.a

CHORES_PATH=$(DEV_PATH)/frame/chores

CHORES_FARM_PATH=$(CHORES_PATH)/farm
CHORES_FARM_INC=-I$(CHORES_FARM_PATH)/
CHORES_FARM_LIB=$(CHORES_FARM_PATH)/chores_farm.a

SERVICE_PATH=$(DEV_PATH)/service

SERVICE_LOGGER_PATH=$(SERVICE_PATH)/logger_service
SERVICE_LOGGER_INC=-I$(SERVICE_LOGGER_PATH)/
SERVICE_LOGGER_LIB=$(SERVICE_LOGGER_PATH)/logger.a

SERVICE_DATA_PATH=$(SERVICE_PATH)/data_service

SERVICE_SQLMGR_PATH=$(SERVICE_DATA_PATH)/sqlmgr
SERVICE_SQLMGR_INC=-I$(SERVICE_SQLMGR_PATH)/
SERVICE_SQLMGR_LIB=$(SERVICE_SQLMGR_PATH)/sqlmgr.a

SERVICE_LOADER_PATH=$(SERVICE_DATA_PATH)/loader
SERVICE_LOADER_INC=-I$(SERVICE_LOADER_PATH)/
SERVICE_LOADER_LIB=$(SERVICE_LOADER_PATH)/loader.a

SERVICE_WRITER_PATH=$(SERVICE_DATA_PATH)/writer
SERVICE_WRITER_INC=-I$(SERVICE_WRITER_PATH)/
SERVICE_WRITER_LIB=$(SERVICE_WRITER_PATH)/writer.a

SERVICE_ROLE_PATH=$(SERVICE_PATH)/role_service
SERVICE_ROLE_INC=-I$(SERVICE_ROLE_PATH)/
SERVICE_ROLE_LIB=$(SERVICE_ROLE_PATH)/role.a

SERVICE_CENTER_PATH=$(SERVICE_PATH)/center_service
SERVICE_CENTER_INC=-I$(SERVICE_CENTER_PATH)/
SERVICE_CENTER_LIB=$(SERVICE_CENTER_PATH)/center.a

SERVICE_GAME_PATH=$(SERVICE_PATH)/game_service
SERVICE_GAME_INC=-I$(SERVICE_GAME_PATH)/
SERVICE_GAME_LIB=$(SERVICE_GAME_PATH)/game.a

SERVICE_GATE_PATH=$(SERVICE_PATH)/gate_service
SERVICE_GATE_INC=-I$(SERVICE_GATE_PATH)/
SERVICE_GATE_LIB=$(SERVICE_GATE_PATH)/gate.a

SERVICE_WATCHDOG_PATH=$(SERVICE_PATH)/watchdog_service
SERVICE_WATCHDOG_INC=-I$(SERVICE_WATCHDOG_PATH)/
SERVICE_WATCHDOG_LIB=$(SERVICE_WATCHDOG_PATH)/watchdog.a

SERVICE_SENDER_PATH=$(SERVICE_PATH)/sender_service
SERVICE_SENDER_INC=-I$(SERVICE_SENDER_PATH)/
SERVICE_SENDER_LIB=$(SERVICE_SENDER_PATH)/sender.a

SERVICE_AGENT_PATH=$(SERVICE_PATH)/agent_service
SERVICE_AGENT_INC=-I$(SERVICE_AGENT_PATH)/
SERVICE_AGENT_LIB=$(SERVICE_AGENT_PATH)/agent.a

SERVICE_CHORES_PATH=$(SERVICE_PATH)/chores_service
SERVICE_CHORES_INC=-I$(SERVICE_CHORES_PATH)/
SERVICE_CHORES_LIB=$(SERVICE_CHORES_PATH)/chores.a

SERVICE_NODE_PATH=$(SERVICE_PATH)/node_service
SERVICE_NODE_INC=-I$(SERVICE_NODE_PATH)/
SERVICE_NODE_LIB=$(SERVICE_NODE_PATH)/node.a

LUA_TINK_PATH=$(DEV_PATH)/tpl/LuaTinker
LUA_TINK_INC=-I$(LUA_TINK_PATH)/
LUA_TINK_LIB=$(LUA_TINK_PATH)/libluatinker.a
