--装备表
 local autoTable = {
	[151101]={
		name="青铜剑",
		quality=3,
		needLv=1,
		type = "weapon",
		kind = 1,
		lock=1,
		recycleGold=240,
		describe="    由青铜所制的朴素利剑。",
		attr = {
			physcAtkMin=180,
			physcAtkMax=220,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151102]={
		name="猎魔剑",
		quality=1,
		needLv=10,
		type = "weapon",
		kind = 1,
		recycleGold=200,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=349,
			physcAtkMax=411,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151103]={
		name="猎魔剑",
		quality=3,
		needLv=10,
		type = "weapon",
		kind = 1,
		needGold=4000,
		recycleGold=400,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=393,
			physcAtkMax=480,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151104]={
		name="猎魔剑",
		quality=4,
		needLv=10,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=442,
			physcAtkMax=539,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155001,
		store=2,
	},
	[151105]={
		name="无极剑",
		quality=1,
		needLv=20,
		type = "weapon",
		kind = 1,
		recycleGold=360,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=516,
			physcAtkMax=631,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151106]={
		name="无极剑",
		quality=3,
		needLv=20,
		type = "weapon",
		kind = 1,
		needGold=7200,
		recycleGold=720,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=580,
			physcAtkMax=709,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151107]={
		name="无极剑",
		quality=4,
		needLv=20,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=653,
			physcAtkMax=798,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155002,
		store=2,
	},
	[151108]={
		name="赤炎剑",
		quality=1,
		needLv=30,
		type = "weapon",
		kind = 1,
		recycleGold=600,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=696,
			physcAtkMax=850,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151109]={
		name="赤炎剑",
		quality=3,
		needLv=30,
		type = "weapon",
		kind = 1,
		needGold=12000,
		recycleGold=1200,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=760,
			physcAtkMax=929,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151110]={
		name="赤炎剑",
		quality=4,
		needLv=30,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=831,
			physcAtkMax=1015,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155003,
		store=2,
	},
	[151111]={
		name="月影剑",
		quality=1,
		needLv=40,
		type = "weapon",
		kind = 1,
		recycleGold=920,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=882,
			physcAtkMax=1078,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151112]={
		name="月影剑",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 1,
		needGold=18400,
		recycleGold=1840,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=936,
			physcAtkMax=1144,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151113]={
		name="月影剑",
		quality=4,
		needLv=40,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=3680,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=993,
			physcAtkMax=1214,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155004,
		store=2,
	},
	[151114]={
		name="月影剑",
		quality=5,
		needLv=40,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=1075,
			physcAtkMax=1316,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155005,
		store=2,
	},
	[151115]={
		name="星尘剑",
		quality=1,
		needLv=50,
		type = "weapon",
		kind = 1,
		recycleGold=1320,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1055,
			physcAtkMax=1290,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151116]={
		name="星尘剑",
		quality=3,
		needLv=50,
		type = "weapon",
		kind = 1,
		needGold=26400,
		recycleGold=2640,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1120,
			physcAtkMax=1369,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151117]={
		name="星尘剑",
		quality=4,
		needLv=50,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=5280,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1189,
			physcAtkMax=1452,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155006,
		store=2,
	},
	[151118]={
		name="星尘剑",
		quality=5,
		needLv=50,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1277,
			physcAtkMax=1563,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155007,
		store=2,
	},
	[151119]={
		name="玄黄破坚剑",
		quality=1,
		needLv=60,
		type = "weapon",
		kind = 1,
		recycleGold=1800,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1228,
			physcAtkMax=1501,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151120]={
		name="玄黄破坚剑",
		quality=3,
		needLv=60,
		type = "weapon",
		kind = 1,
		needGold=36000,
		recycleGold=3600,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1304,
			physcAtkMax=1593,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		store=2,
	},
	[151121]={
		name="玄黄破坚剑",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=7200,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1383,
			physcAtkMax=1691,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155008,
		store=2,
	},
	[151122]={
		name="玄黄破坚剑",
		quality=5,
		needLv=60,
		type = "weapon",
		kind = 1,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1452,
			physcAtkMax=1776,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155009,
		store=2,
	},
	[151201]={
		name="短弓",
		quality=3,
		needLv=1,
		type = "weapon",
		kind = 2,
		lock=1,
		recycleGold=240,
		describe="    由精木制作的强力短弓。",
		attr = {
			physcAtkMin=180,
			physcAtkMax=220,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151202]={
		name="猎魔弓",
		quality=1,
		needLv=10,
		type = "weapon",
		kind = 2,
		recycleGold=200,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=349,
			physcAtkMax=411,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151203]={
		name="猎魔弓",
		quality=3,
		needLv=10,
		type = "weapon",
		kind = 2,
		needGold=4000,
		recycleGold=400,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=393,
			physcAtkMax=480,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151204]={
		name="猎魔弓",
		quality=4,
		needLv=10,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin=442,
			physcAtkMax=539,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155001,
		store=2,
	},
	[151205]={
		name="无极弓",
		quality=1,
		needLv=20,
		type = "weapon",
		kind = 2,
		recycleGold=360,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=516,
			physcAtkMax=631,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151206]={
		name="无极弓",
		quality=3,
		needLv=20,
		type = "weapon",
		kind = 2,
		needGold=7200,
		recycleGold=720,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=580,
			physcAtkMax=709,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151207]={
		name="无极弓",
		quality=4,
		needLv=20,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin=653,
			physcAtkMax=798,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155002,
		store=2,
	},
	[151208]={
		name="赤炎弓",
		quality=1,
		needLv=30,
		type = "weapon",
		kind = 2,
		recycleGold=600,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=696,
			physcAtkMax=850,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151209]={
		name="赤炎弓",
		quality=3,
		needLv=30,
		type = "weapon",
		kind = 2,
		needGold=12000,
		recycleGold=1200,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=760,
			physcAtkMax=929,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151210]={
		name="赤炎弓",
		quality=4,
		needLv=30,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin=831,
			physcAtkMax=1015,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155003,
		store=2,
	},
	[151211]={
		name="月影弓",
		quality=1,
		needLv=40,
		type = "weapon",
		kind = 2,
		recycleGold=920,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=882,
			physcAtkMax=1078,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151212]={
		name="月影弓",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 2,
		needGold=18400,
		recycleGold=1840,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=936,
			physcAtkMax=1144,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151213]={
		name="月影弓",
		quality=4,
		needLv=40,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=3680,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=993,
			physcAtkMax=1214,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155004,
		store=2,
	},
	[151214]={
		name="月影弓",
		quality=5,
		needLv=40,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin=1075,
			physcAtkMax=1316,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155005,
		store=2,
	},
	[151215]={
		name="星尘弓",
		quality=1,
		needLv=50,
		type = "weapon",
		kind = 2,
		recycleGold=1320,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1055,
			physcAtkMax=1290,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151216]={
		name="星尘弓",
		quality=3,
		needLv=50,
		type = "weapon",
		kind = 2,
		needGold=26400,
		recycleGold=2640,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1120,
			physcAtkMax=1369,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151217]={
		name="星尘弓",
		quality=4,
		needLv=50,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=5280,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1189,
			physcAtkMax=1452,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155006,
		store=2,
	},
	[151218]={
		name="星尘弓",
		quality=5,
		needLv=50,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin=1277,
			physcAtkMax=1563,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155007,
		store=2,
	},
	[151219]={
		name="玄黄破坚弓",
		quality=1,
		needLv=60,
		type = "weapon",
		kind = 2,
		recycleGold=1800,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1228,
			physcAtkMax=1501,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151220]={
		name="玄黄破坚弓",
		quality=3,
		needLv=60,
		type = "weapon",
		kind = 2,
		needGold=36000,
		recycleGold=3600,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1304,
			physcAtkMax=1593,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		store=2,
	},
	[151221]={
		name="玄黄破坚弓",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=7200,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1383,
			physcAtkMax=1691,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155008,
		store=2,
	},
	[151222]={
		name="玄黄破坚弓",
		quality=5,
		needLv=60,
		type = "weapon",
		kind = 2,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin=1452,
			physcAtkMax=1776,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155009,
		store=2,
	},
	[151301]={
		name="木杖",
		quality=3,
		needLv=1,
		type = "weapon",
		kind = 3,
		lock=1,
		recycleGold=240,
		describe="    年代久远封尘的法杖。",
		attr = {
			magicAtkMin=180,
			magicAtkMax=220,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151302]={
		name="猎魔杖",
		quality=1,
		needLv=10,
		type = "weapon",
		kind = 3,
		recycleGold=200,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicAtkMin=349,
			magicAtkMax=411,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151303]={
		name="猎魔杖",
		quality=3,
		needLv=10,
		type = "weapon",
		kind = 3,
		needGold=4000,
		recycleGold=400,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicAtkMin=393,
			magicAtkMax=480,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151304]={
		name="猎魔杖",
		quality=4,
		needLv=10,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicAtkMin=442,
			magicAtkMax=539,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155001,
		store=2,
	},
	[151305]={
		name="无极杖",
		quality=1,
		needLv=20,
		type = "weapon",
		kind = 3,
		recycleGold=360,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicAtkMin=516,
			magicAtkMax=631,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151306]={
		name="无极杖",
		quality=3,
		needLv=20,
		type = "weapon",
		kind = 3,
		needGold=7200,
		recycleGold=720,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicAtkMin=580,
			magicAtkMax=709,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151307]={
		name="无极杖",
		quality=4,
		needLv=20,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicAtkMin=653,
			magicAtkMax=798,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155002,
		store=2,
	},
	[151308]={
		name="赤炎杖",
		quality=1,
		needLv=30,
		type = "weapon",
		kind = 3,
		recycleGold=600,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			magicAtkMin=696,
			magicAtkMax=850,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151309]={
		name="赤炎杖",
		quality=3,
		needLv=30,
		type = "weapon",
		kind = 3,
		needGold=12000,
		recycleGold=1200,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicAtkMin=760,
			magicAtkMax=929,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151310]={
		name="赤炎杖",
		quality=4,
		needLv=30,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicAtkMin=831,
			magicAtkMax=1015,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155003,
		store=2,
	},
	[151311]={
		name="月影杖",
		quality=1,
		needLv=40,
		type = "weapon",
		kind = 3,
		recycleGold=920,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicAtkMin=882,
			magicAtkMax=1078,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151312]={
		name="月影杖",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 3,
		needGold=18400,
		recycleGold=1840,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicAtkMin=936,
			magicAtkMax=1144,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151313]={
		name="月影杖",
		quality=4,
		needLv=40,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=3680,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicAtkMin=993,
			magicAtkMax=1214,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155004,
		store=2,
	},
	[151314]={
		name="月影杖",
		quality=5,
		needLv=40,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicAtkMin=1075,
			magicAtkMax=1316,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155005,
		store=2,
	},
	[151315]={
		name="星尘杖",
		quality=1,
		needLv=50,
		type = "weapon",
		kind = 3,
		recycleGold=1320,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicAtkMin=1055,
			magicAtkMax=1290,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151316]={
		name="星尘杖",
		quality=3,
		needLv=50,
		type = "weapon",
		kind = 3,
		needGold=26400,
		recycleGold=2640,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicAtkMin=1120,
			magicAtkMax=1369,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151317]={
		name="星尘杖",
		quality=4,
		needLv=50,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=5280,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicAtkMin=1189,
			magicAtkMax=1452,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155006,
		store=2,
	},
	[151318]={
		name="星尘杖",
		quality=5,
		needLv=50,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicAtkMin=1277,
			magicAtkMax=1563,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155007,
		store=2,
	},
	[151319]={
		name="玄黄破坚杖",
		quality=1,
		needLv=60,
		type = "weapon",
		kind = 3,
		recycleGold=1800,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicAtkMin=1228,
			magicAtkMax=1501,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151320]={
		name="玄黄破坚杖",
		quality=3,
		needLv=60,
		type = "weapon",
		kind = 3,
		needGold=36000,
		recycleGold=3600,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicAtkMin=1304,
			magicAtkMax=1593,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		store=2,
	},
	[151321]={
		name="玄黄破坚杖",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=7200,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicAtkMin=1383,
			magicAtkMax=1691,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155008,
		store=2,
	},
	[151322]={
		name="玄黄破坚杖",
		quality=5,
		needLv=60,
		type = "weapon",
		kind = 3,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicAtkMin=1452,
			magicAtkMax=1776,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155009,
		store=2,
	},
	[151401]={
		name="麻布长袍",
		quality=3,
		needLv=1,
		type = "armor",
		kind = 4,
		lock=1,
		recycleGold=228,
		describe="    仅供保暖的遮身长袍。",
		attr = {
			physcDef=22,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151402]={
		name="猎魔袍",
		quality=1,
		needLv=10,
		type = "armor",
		kind = 4,
		recycleGold=190,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=42,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151403]={
		name="猎魔袍",
		quality=3,
		needLv=10,
		type = "armor",
		kind = 4,
		needGold=3800,
		recycleGold=380,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=48,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151404]={
		name="猎魔袍",
		quality=4,
		needLv=10,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=760,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=54,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		store=2,
	},
	[151405]={
		name="无极服",
		quality=1,
		needLv=20,
		type = "armor",
		kind = 4,
		recycleGold=342,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=66,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151406]={
		name="无极服",
		quality=3,
		needLv=20,
		type = "armor",
		kind = 4,
		needGold=6840,
		recycleGold=684,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=72,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151407]={
		name="无极服",
		quality=4,
		needLv=20,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=1368,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=78,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		store=2,
	},
	[151408]={
		name="赤炎袍",
		quality=1,
		needLv=30,
		type = "armor",
		kind = 4,
		recycleGold=570,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			physcDef=90,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151409]={
		name="赤炎袍",
		quality=3,
		needLv=30,
		type = "armor",
		kind = 4,
		needGold=11400,
		recycleGold=1140,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=96,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151410]={
		name="赤炎袍",
		quality=4,
		needLv=30,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=2280,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=102,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		store=2,
	},
	[151411]={
		name="月影袍",
		quality=1,
		needLv=40,
		type = "armor",
		kind = 4,
		recycleGold=874,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=114,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151412]={
		name="月影袍",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 4,
		needGold=17480,
		recycleGold=1748,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=120,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151413]={
		name="月影袍",
		quality=4,
		needLv=40,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=3496,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=126,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		store=2,
	},
	[151414]={
		name="月影袍",
		quality=5,
		needLv=40,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=6992,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=136,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		store=2,
	},
	[151415]={
		name="星尘铠",
		quality=1,
		needLv=50,
		type = "armor",
		kind = 4,
		recycleGold=1254,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=138,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151416]={
		name="星尘铠",
		quality=3,
		needLv=50,
		type = "armor",
		kind = 4,
		needGold=25080,
		recycleGold=2508,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=144,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151417]={
		name="星尘铠",
		quality=4,
		needLv=50,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=5016,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=150,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
		store=2,
	},
	[151418]={
		name="星尘铠",
		quality=5,
		needLv=50,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=10032,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=163,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
		store=2,
	},
	[151419]={
		name="玄黄破坚铠",
		quality=1,
		needLv=60,
		type = "armor",
		kind = 4,
		recycleGold=1710,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=162,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151420]={
		name="玄黄破坚铠",
		quality=3,
		needLv=60,
		type = "armor",
		kind = 4,
		needGold=34200,
		recycleGold=3420,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=168,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151421]={
		name="玄黄破坚铠",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=6840,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=174,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155008,
		store=2,
	},
	[151422]={
		name="玄黄破坚铠",
		quality=5,
		needLv=60,
		type = "armor",
		kind = 4,
		lock=1,
		recycleGold=13680,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=210,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155009,
		store=2,
	},
	[151501]={
		name="兽皮护腿",
		quality=3,
		needLv=1,
		type = "armor",
		kind = 5,
		lock=1,
		recycleGold=216,
		describe="    由猛兽的兽皮所制的护腿，具有一定的防护作用。",
		attr = {
			physcDef=22,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151502]={
		name="猎魔护腿",
		quality=1,
		needLv=10,
		type = "armor",
		kind = 5,
		recycleGold=180,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=42,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151503]={
		name="猎魔护腿",
		quality=3,
		needLv=10,
		type = "armor",
		kind = 5,
		needGold=3600,
		recycleGold=360,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=48,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151504]={
		name="猎魔护腿",
		quality=4,
		needLv=10,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=720,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=54,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		store=2,
	},
	[151505]={
		name="无极护腿",
		quality=1,
		needLv=20,
		type = "armor",
		kind = 5,
		recycleGold=324,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=66,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151506]={
		name="无极护腿",
		quality=3,
		needLv=20,
		type = "armor",
		kind = 5,
		needGold=6480,
		recycleGold=648,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=72,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151507]={
		name="无极护腿",
		quality=4,
		needLv=20,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=1296,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=78,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		store=2,
	},
	[151508]={
		name="赤炎护腿",
		quality=1,
		needLv=30,
		type = "armor",
		kind = 5,
		recycleGold=540,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			physcDef=90,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151509]={
		name="赤炎护腿",
		quality=3,
		needLv=30,
		type = "armor",
		kind = 5,
		needGold=10800,
		recycleGold=1080,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=96,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151510]={
		name="赤炎护腿",
		quality=4,
		needLv=30,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=2160,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=102,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		store=2,
	},
	[151511]={
		name="月影裤",
		quality=1,
		needLv=40,
		type = "armor",
		kind = 5,
		recycleGold=828,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=114,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151512]={
		name="月影裤",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 5,
		needGold=16560,
		recycleGold=1656,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=120,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151513]={
		name="月影裤",
		quality=4,
		needLv=40,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=3312,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=126,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		store=2,
	},
	[151514]={
		name="月影裤",
		quality=5,
		needLv=40,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=6624,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=136,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		store=2,
	},
	[151515]={
		name="星尘护腿",
		quality=1,
		needLv=50,
		type = "armor",
		kind = 5,
		recycleGold=1188,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=138,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151516]={
		name="星尘护腿",
		quality=3,
		needLv=50,
		type = "armor",
		kind = 5,
		needGold=23760,
		recycleGold=2376,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=144,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151517]={
		name="星尘护腿",
		quality=4,
		needLv=50,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=4752,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=150,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
		store=2,
	},
	[151518]={
		name="星尘护腿",
		quality=5,
		needLv=50,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=9504,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=163,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
		store=2,
	},
	[151519]={
		name="玄黄破坚下装",
		quality=1,
		needLv=60,
		type = "armor",
		kind = 5,
		recycleGold=1620,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=162,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151520]={
		name="玄黄破坚下装",
		quality=3,
		needLv=60,
		type = "armor",
		kind = 5,
		needGold=32400,
		recycleGold=3240,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=168,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151521]={
		name="玄黄破坚下装",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=6480,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=174,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155008,
		store=2,
	},
	[151522]={
		name="玄黄破坚下装",
		quality=5,
		needLv=60,
		type = "armor",
		kind = 5,
		lock=1,
		recycleGold=12960,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=210,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155009,
		store=2,
	},
	[151601]={
		name="麻布靴",
		quality=3,
		needLv=1,
		type = "armor",
		kind = 6,
		lock=1,
		recycleGold=192,
		describe="    麻布所制的鞋子，具有一定的防护力。",
		attr = {
			physcDef=10,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151602]={
		name="猎魔靴",
		quality=1,
		needLv=10,
		type = "armor",
		kind = 6,
		recycleGold=160,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=20,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151603]={
		name="猎魔靴",
		quality=3,
		needLv=10,
		type = "armor",
		kind = 6,
		needGold=3200,
		recycleGold=320,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=23,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151604]={
		name="猎魔靴",
		quality=4,
		needLv=10,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=640,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef=26,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		store=2,
	},
	[151605]={
		name="无极靴",
		quality=1,
		needLv=20,
		type = "armor",
		kind = 6,
		recycleGold=288,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=32,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151606]={
		name="无极靴",
		quality=3,
		needLv=20,
		type = "armor",
		kind = 6,
		needGold=5760,
		recycleGold=576,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=35,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151607]={
		name="无极靴",
		quality=4,
		needLv=20,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=1152,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef=38,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		store=2,
	},
	[151608]={
		name="赤炎靴",
		quality=1,
		needLv=30,
		type = "armor",
		kind = 6,
		recycleGold=480,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			physcDef=44,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151609]={
		name="赤炎靴",
		quality=3,
		needLv=30,
		type = "armor",
		kind = 6,
		needGold=9600,
		recycleGold=960,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=47,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151610]={
		name="赤炎靴",
		quality=4,
		needLv=30,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=1920,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef=50,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		store=2,
	},
	[151611]={
		name="月影靴",
		quality=1,
		needLv=40,
		type = "armor",
		kind = 6,
		recycleGold=736,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=56,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151612]={
		name="月影靴",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 6,
		needGold=14720,
		recycleGold=1472,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=59,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151613]={
		name="月影靴",
		quality=4,
		needLv=40,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=2944,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=62,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		store=2,
	},
	[151614]={
		name="月影靴",
		quality=5,
		needLv=40,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=5888,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef=67,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		store=2,
	},
	[151615]={
		name="星尘靴",
		quality=1,
		needLv=50,
		type = "armor",
		kind = 6,
		recycleGold=1056,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=68,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151616]={
		name="星尘靴",
		quality=3,
		needLv=50,
		type = "armor",
		kind = 6,
		needGold=21120,
		recycleGold=2112,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=71,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151617]={
		name="星尘靴",
		quality=4,
		needLv=50,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=4224,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=74,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
		store=2,
	},
	[151618]={
		name="星尘靴",
		quality=5,
		needLv=50,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=8448,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef=80,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
		store=2,
	},
	[151619]={
		name="玄黄破坚战靴",
		quality=1,
		needLv=60,
		type = "armor",
		kind = 6,
		recycleGold=1440,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=80,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151620]={
		name="玄黄破坚战靴",
		quality=3,
		needLv=60,
		type = "armor",
		kind = 6,
		needGold=28800,
		recycleGold=2880,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=83,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151621]={
		name="玄黄破坚战靴",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=5760,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=86,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155008,
		store=2,
	},
	[151622]={
		name="玄黄破坚战靴",
		quality=5,
		needLv=60,
		type = "armor",
		kind = 6,
		lock=1,
		recycleGold=11520,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef=104,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155009,
		store=2,
	},
	[151701]={
		name="骨制项链",
		quality=3,
		needLv=1,
		type = "jewelry",
		kind = 7,
		lock=1,
		recycleGold=312,
		describe="    由蛮荒兽骨所制，虽然没啥用，但是也能用来辟邪的。",
		attr = {
			magicDef=27,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151702]={
		name="猎魔项链",
		quality=1,
		needLv=10,
		type = "jewelry",
		kind = 7,
		recycleGold=260,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=53,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151703]={
		name="猎魔项链",
		quality=3,
		needLv=10,
		type = "jewelry",
		kind = 7,
		needGold=5200,
		recycleGold=520,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=59,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151704]={
		name="猎魔项链",
		quality=4,
		needLv=10,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=1040,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=65,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		store=2,
	},
	[151705]={
		name="无极项链",
		quality=1,
		needLv=20,
		type = "jewelry",
		kind = 7,
		recycleGold=468,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=83,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151706]={
		name="无极项链",
		quality=3,
		needLv=20,
		type = "jewelry",
		kind = 7,
		needGold=9360,
		recycleGold=936,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=89,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151707]={
		name="无极项链",
		quality=4,
		needLv=20,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=1872,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=95,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		store=2,
	},
	[151708]={
		name="赤炎项链",
		quality=1,
		needLv=30,
		type = "jewelry",
		kind = 7,
		recycleGold=780,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			magicDef=113,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151709]={
		name="赤炎项链",
		quality=3,
		needLv=30,
		type = "jewelry",
		kind = 7,
		needGold=15600,
		recycleGold=1560,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicDef=119,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151710]={
		name="赤炎项链",
		quality=4,
		needLv=30,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=3120,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicDef=125,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		store=2,
	},
	[151711]={
		name="月影项链",
		quality=1,
		needLv=40,
		type = "jewelry",
		kind = 7,
		recycleGold=1196,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=143,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151712]={
		name="月影项链",
		quality=3,
		needLv=40,
		type = "jewelry",
		kind = 7,
		needGold=23920,
		recycleGold=2392,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=149,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151713]={
		name="月影项链",
		quality=4,
		needLv=40,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=4784,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=155,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		store=2,
	},
	[151714]={
		name="月影项链",
		quality=5,
		needLv=40,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=9568,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=169,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		store=2,
	},
	[151715]={
		name="星尘项链",
		quality=1,
		needLv=50,
		type = "jewelry",
		kind = 7,
		recycleGold=1716,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=173,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151716]={
		name="星尘项链",
		quality=3,
		needLv=50,
		type = "jewelry",
		kind = 7,
		needGold=34320,
		recycleGold=3432,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=179,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151717]={
		name="星尘项链",
		quality=4,
		needLv=50,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=6864,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=185,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
		store=2,
	},
	[151718]={
		name="星尘项链",
		quality=5,
		needLv=50,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=13728,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=203,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
		store=2,
	},
	[151719]={
		name="玄黄破坚项链",
		quality=1,
		needLv=60,
		type = "jewelry",
		kind = 7,
		recycleGold=2340,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=203,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151720]={
		name="玄黄破坚项链",
		quality=3,
		needLv=60,
		type = "jewelry",
		kind = 7,
		needGold=46800,
		recycleGold=4680,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=209,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151721]={
		name="玄黄破坚项链",
		quality=4,
		needLv=60,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=9360,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=215,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155008,
		store=2,
	},
	[151722]={
		name="玄黄破坚项链",
		quality=5,
		needLv=60,
		type = "jewelry",
		kind = 7,
		lock=1,
		recycleGold=18720,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=230,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155009,
		store=2,
	},
	[151801]={
		name="暗淡的戒指",
		quality=3,
		needLv=1,
		type = "jewelry",
		kind = 8,
		lock=1,
		recycleGold=288,
		describe="    不知道那里捡来的暗淡戒指。",
		attr = {
			magicDef=27,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151802]={
		name="猎魔戒指",
		quality=1,
		needLv=10,
		type = "jewelry",
		kind = 8,
		recycleGold=240,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=53,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151803]={
		name="猎魔戒指",
		quality=3,
		needLv=10,
		type = "jewelry",
		kind = 8,
		needGold=4800,
		recycleGold=480,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=59,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151804]={
		name="猎魔戒指",
		quality=4,
		needLv=10,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=960,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef=65,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		store=2,
	},
	[151805]={
		name="无极戒指",
		quality=1,
		needLv=20,
		type = "jewelry",
		kind = 8,
		recycleGold=432,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=83,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151806]={
		name="无极戒指",
		quality=3,
		needLv=20,
		type = "jewelry",
		kind = 8,
		needGold=8640,
		recycleGold=864,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=89,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151807]={
		name="无极戒指",
		quality=4,
		needLv=20,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=1728,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef=95,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		store=2,
	},
	[151808]={
		name="赤炎戒指",
		quality=1,
		needLv=30,
		type = "jewelry",
		kind = 8,
		recycleGold=720,
		describe="    集天地灵气，借赤炎之火应运而生 \n\t\t---喻名赤炎。",
		attr = {
			magicDef=113,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151809]={
		name="赤炎戒指",
		quality=3,
		needLv=30,
		type = "jewelry",
		kind = 8,
		needGold=14400,
		recycleGold=1440,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicDef=119,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151810]={
		name="赤炎戒指",
		quality=4,
		needLv=30,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=2880,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicDef=125,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		store=2,
	},
	[151811]={
		name="月影戒指",
		quality=1,
		needLv=40,
		type = "jewelry",
		kind = 8,
		recycleGold=1104,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=143,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151812]={
		name="月影戒指",
		quality=3,
		needLv=40,
		type = "jewelry",
		kind = 8,
		needGold=22080,
		recycleGold=2208,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=149,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151813]={
		name="月影戒指",
		quality=4,
		needLv=40,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=4416,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=155,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		store=2,
	},
	[151814]={
		name="月影戒指",
		quality=5,
		needLv=40,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=8832,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef=169,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		store=2,
	},
	[151815]={
		name="星尘戒指",
		quality=1,
		needLv=50,
		type = "jewelry",
		kind = 8,
		recycleGold=1584,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=173,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151816]={
		name="星尘戒指",
		quality=3,
		needLv=50,
		type = "jewelry",
		kind = 8,
		needGold=31680,
		recycleGold=3168,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=179,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151817]={
		name="星尘戒指",
		quality=4,
		needLv=50,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=6336,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=185,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
		store=2,
	},
	[151818]={
		name="星尘戒指",
		quality=5,
		needLv=50,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=12672,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef=203,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
		store=2,
	},
	[151819]={
		name="玄黄破坚戒指",
		quality=1,
		needLv=60,
		type = "jewelry",
		kind = 8,
		recycleGold=2160,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=203,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151820]={
		name="玄黄破坚戒指",
		quality=3,
		needLv=60,
		type = "jewelry",
		kind = 8,
		needGold=43200,
		recycleGold=4320,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=209,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		store=2,
	},
	[151821]={
		name="玄黄破坚戒指",
		quality=4,
		needLv=60,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=8640,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=215,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155008,
		store=2,
	},
	[151822]={
		name="玄黄破坚戒指",
		quality=5,
		needLv=60,
		type = "jewelry",
		kind = 8,
		lock=1,
		recycleGold=17280,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef=230,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155009,
		store=2,
	},
}
function GetTable()
	return autoTable
end
