--市场升级表
 local autoTable = {
	[111101] = {
		name = "1级力量石",
		Lv = 1,
		quality = 1,
		complex = 111102,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加6点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			strength = 8,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111102] = {
		name = "2级力量石",
		Lv = 2,
		quality = 1,
		complex = 111103,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加12点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111103] = {
		name = "3级力量石",
		Lv = 3,
		quality = 2,
		complex = 111104,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加18点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 24,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111104] = {
		name = "4级力量石",
		Lv = 4,
		quality = 2,
		complex = 111105,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加24点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111105] = {
		name = "5级力量石",
		Lv = 5,
		quality = 3,
		complex = 111106,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加30点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111106] = {
		name = "6级力量石",
		Lv = 6,
		quality = 3,
		complex = 111107,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加36点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111107] = {
		name = "7级力量石",
		Lv = 7,
		quality = 4,
		complex = 111108,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加42点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 56,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111108] = {
		name = "8级力量石",
		Lv = 8,
		quality = 4,
		complex = 111109,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加48点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111109] = {
		name = "9级力量石",
		Lv = 9,
		quality = 5,
		complex = 111110,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加54点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 72,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111110] = {
		name = "10级力量石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点力量，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			strength = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "strength",
	},
	[111201] = {
		name = "1级智力石",
		Lv = 1,
		quality = 1,
		complex = 111202,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加6点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			intellect = 8,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111202] = {
		name = "2级智力石",
		Lv = 2,
		quality = 1,
		complex = 111203,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加12点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111203] = {
		name = "3级智力石",
		Lv = 3,
		quality = 2,
		complex = 111204,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加18点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 24,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111204] = {
		name = "4级智力石",
		Lv = 4,
		quality = 2,
		complex = 111205,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加24点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111205] = {
		name = "5级智力石",
		Lv = 5,
		quality = 3,
		complex = 111206,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加30点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111206] = {
		name = "6级智力石",
		Lv = 6,
		quality = 3,
		complex = 111207,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加36点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111207] = {
		name = "7级智力石",
		Lv = 7,
		quality = 4,
		complex = 111208,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加42点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 56,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111208] = {
		name = "8级智力石",
		Lv = 8,
		quality = 4,
		complex = 111209,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加48点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111209] = {
		name = "9级智力石",
		Lv = 9,
		quality = 5,
		complex = 111210,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加54点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 72,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111210] = {
		name = "10级智力石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点智力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			intellect = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "intellect",
	},
	[111301] = {
		name = "1级敏捷石",
		Lv = 1,
		quality = 1,
		complex = 111302,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加6点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			agility = 8,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111302] = {
		name = "2级敏捷石",
		Lv = 2,
		quality = 1,
		complex = 111303,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加12点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111303] = {
		name = "3级敏捷石",
		Lv = 3,
		quality = 2,
		complex = 111304,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加18点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 24,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111304] = {
		name = "4级敏捷石",
		Lv = 4,
		quality = 2,
		complex = 111305,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加24点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111305] = {
		name = "5级敏捷石",
		Lv = 5,
		quality = 3,
		complex = 111306,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加30点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111306] = {
		name = "6级敏捷石",
		Lv = 6,
		quality = 3,
		complex = 111307,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加36点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111307] = {
		name = "7级敏捷石",
		Lv = 7,
		quality = 4,
		complex = 111308,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加42点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 56,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111308] = {
		name = "8级敏捷石",
		Lv = 8,
		quality = 4,
		complex = 111309,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加48点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111309] = {
		name = "9级敏捷石",
		Lv = 9,
		quality = 5,
		complex = 111310,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加54点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 72,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111310] = {
		name = "10级敏捷石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点敏捷，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			agility = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "agility",
	},
	[111401] = {
		name = "1级统帅石",
		Lv = 1,
		quality = 1,
		complex = 111402,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加6点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			captain = 8,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111402] = {
		name = "2级统帅石",
		Lv = 2,
		quality = 1,
		complex = 111403,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加12点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111403] = {
		name = "3级统帅石",
		Lv = 3,
		quality = 2,
		complex = 111404,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加18点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 24,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111404] = {
		name = "4级统帅石",
		Lv = 4,
		quality = 2,
		complex = 111405,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加24点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111405] = {
		name = "5级统帅石",
		Lv = 5,
		quality = 3,
		complex = 111406,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加30点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111406] = {
		name = "6级统帅石",
		Lv = 6,
		quality = 3,
		complex = 111407,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加36点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111407] = {
		name = "7级统帅石",
		Lv = 7,
		quality = 4,
		complex = 111408,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加42点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 56,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111408] = {
		name = "8级统帅石",
		Lv = 8,
		quality = 4,
		complex = 111409,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加48点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111409] = {
		name = "9级统帅石",
		Lv = 9,
		quality = 5,
		complex = 111410,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加54点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 72,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111410] = {
		name = "10级统帅石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点统帅，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			captain = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "captain",
	},
	[111501] = {
		name = "1级物攻石",
		Lv = 1,
		quality = 1,
		complex = 111502,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加25点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			physcAtk = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111502] = {
		name = "2级物攻石",
		Lv = 2,
		quality = 1,
		complex = 111503,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加50点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111503] = {
		name = "3级物攻石",
		Lv = 3,
		quality = 2,
		complex = 111504,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加75点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 120,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111504] = {
		name = "4级物攻石",
		Lv = 4,
		quality = 2,
		complex = 111505,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加100点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 160,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111505] = {
		name = "5级物攻石",
		Lv = 5,
		quality = 3,
		complex = 111506,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加125点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 200,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111506] = {
		name = "6级物攻石",
		Lv = 6,
		quality = 3,
		complex = 111507,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加150点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 240,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111507] = {
		name = "7级物攻石",
		Lv = 7,
		quality = 4,
		complex = 111508,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加175点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 280,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111508] = {
		name = "8级物攻石",
		Lv = 8,
		quality = 4,
		complex = 111509,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加200点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 320,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111509] = {
		name = "9级物攻石",
		Lv = 9,
		quality = 5,
		complex = 111510,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加225点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 360,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111510] = {
		name = "10级物攻石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加250点物理攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcAtk = 400,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcAtk",
	},
	[111601] = {
		name = "1级魔攻石",
		Lv = 1,
		quality = 1,
		complex = 111602,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加25点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			magicAtk = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111602] = {
		name = "2级魔攻石",
		Lv = 2,
		quality = 1,
		complex = 111603,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加50点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111603] = {
		name = "3级魔攻石",
		Lv = 3,
		quality = 2,
		complex = 111604,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加75点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 120,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111604] = {
		name = "4级魔攻石",
		Lv = 4,
		quality = 2,
		complex = 111605,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加100点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 160,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111605] = {
		name = "5级魔攻石",
		Lv = 5,
		quality = 3,
		complex = 111606,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加125点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 200,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111606] = {
		name = "6级魔攻石",
		Lv = 6,
		quality = 3,
		complex = 111607,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加150点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 240,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111607] = {
		name = "7级魔攻石",
		Lv = 7,
		quality = 4,
		complex = 111608,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加175点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 280,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111608] = {
		name = "8级魔攻石",
		Lv = 8,
		quality = 4,
		complex = 111609,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加200点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 320,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111609] = {
		name = "9级魔攻石",
		Lv = 9,
		quality = 5,
		complex = 111610,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加225点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 360,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111610] = {
		name = "10级魔攻石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加250点魔法攻击，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicAtk = 400,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicAtk",
	},
	[111701] = {
		name = "1级物防石",
		Lv = 1,
		quality = 1,
		complex = 111702,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加10点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			physcDef = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111702] = {
		name = "2级物防石",
		Lv = 2,
		quality = 1,
		complex = 111703,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加20点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111703] = {
		name = "3级物防石",
		Lv = 3,
		quality = 2,
		complex = 111704,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加30点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111704] = {
		name = "4级物防石",
		Lv = 4,
		quality = 2,
		complex = 111705,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加40点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111705] = {
		name = "5级物防石",
		Lv = 5,
		quality = 3,
		complex = 111706,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加50点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111706] = {
		name = "6级物防石",
		Lv = 6,
		quality = 3,
		complex = 111707,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 96,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111707] = {
		name = "7级物防石",
		Lv = 7,
		quality = 4,
		complex = 111708,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加70点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 112,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111708] = {
		name = "8级物防石",
		Lv = 8,
		quality = 4,
		complex = 111709,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加80点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 128,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111709] = {
		name = "9级物防石",
		Lv = 9,
		quality = 5,
		complex = 111710,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加90点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 144,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111710] = {
		name = "10级物防石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加100点物理防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			physcDef = 160,
		},
		areaType = "gem",
		type = "gem",
		kind = "physcDef",
	},
	[111801] = {
		name = "1级法防石",
		Lv = 1,
		quality = 1,
		complex = 111802,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加10点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			magicDef = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111802] = {
		name = "2级法防石",
		Lv = 2,
		quality = 1,
		complex = 111803,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加20点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111803] = {
		name = "3级法防石",
		Lv = 3,
		quality = 2,
		complex = 111804,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加30点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111804] = {
		name = "4级法防石",
		Lv = 4,
		quality = 2,
		complex = 111805,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加40点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111805] = {
		name = "5级法防石",
		Lv = 5,
		quality = 3,
		complex = 111806,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加50点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111806] = {
		name = "6级法防石",
		Lv = 6,
		quality = 3,
		complex = 111807,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 96,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111807] = {
		name = "7级法防石",
		Lv = 7,
		quality = 4,
		complex = 111808,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加70点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 112,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111808] = {
		name = "8级法防石",
		Lv = 8,
		quality = 4,
		complex = 111809,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加80点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 128,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111809] = {
		name = "9级法防石",
		Lv = 9,
		quality = 5,
		complex = 111810,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加90点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 144,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111810] = {
		name = "10级法防石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加100点魔法防御，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			magicDef = 160,
		},
		areaType = "gem",
		type = "gem",
		kind = "magicDef",
	},
	[111901] = {
		name = "1级兵力石",
		Lv = 1,
		quality = 1,
		complex = 111902,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加70点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			hpMax = 70,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111902] = {
		name = "2级兵力石",
		Lv = 2,
		quality = 1,
		complex = 111903,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加140点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 140,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111903] = {
		name = "3级兵力石",
		Lv = 3,
		quality = 2,
		complex = 111904,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加210点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 210,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111904] = {
		name = "4级兵力石",
		Lv = 4,
		quality = 2,
		complex = 111905,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加280点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 280,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111905] = {
		name = "5级兵力石",
		Lv = 5,
		quality = 3,
		complex = 111906,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加350点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 350,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111906] = {
		name = "6级兵力石",
		Lv = 6,
		quality = 3,
		complex = 111907,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加420点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 420,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111907] = {
		name = "7级兵力石",
		Lv = 7,
		quality = 4,
		complex = 111908,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加490点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 490,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111908] = {
		name = "8级兵力石",
		Lv = 8,
		quality = 4,
		complex = 111909,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加560点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 560,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111909] = {
		name = "9级兵力石",
		Lv = 9,
		quality = 5,
		complex = 111910,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加630点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 630,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[111910] = {
		name = "10级兵力石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加700点兵力，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			hpMax = 700,
		},
		areaType = "gem",
		type = "gem",
		kind = "hpMax",
	},
	[101038] = {
		name = "藏宝图碎片",
		Lv = 1,
		quality = 3,
		complex = 101041,
		class = "normal",
		recycleGold = 1,
		describe = "可拼凑成森林藏宝图的碎片",
		areaType = "prop",
		type = "piece",
	},
	[112001] = {
		name = "1级速度石",
		Lv = 1,
		quality = 1,
		complex = 112002,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加6点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 1,
		attr = {
			speed = 8,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112002] = {
		name = "2级速度石",
		Lv = 2,
		quality = 1,
		complex = 112003,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加12点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 16,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112003] = {
		name = "3级速度石",
		Lv = 3,
		quality = 2,
		complex = 112004,
		mall = 4,
		class = "gem",
		needIngot = 30,
		recycleGold = 10,
		describe = "镶嵌装备后增加18点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 24,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112004] = {
		name = "4级速度石",
		Lv = 4,
		quality = 2,
		complex = 112005,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加24点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 32,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112005] = {
		name = "5级速度石",
		Lv = 5,
		quality = 3,
		complex = 112006,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加30点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 40,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112006] = {
		name = "6级速度石",
		Lv = 6,
		quality = 3,
		complex = 112007,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加36点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 48,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112007] = {
		name = "7级速度石",
		Lv = 7,
		quality = 4,
		complex = 112008,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加42点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 56,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112008] = {
		name = "8级速度石",
		Lv = 8,
		quality = 4,
		complex = 112009,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加48点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 64,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112009] = {
		name = "9级速度石",
		Lv = 9,
		quality = 5,
		complex = 112010,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加54点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 72,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
	[112010] = {
		name = "10级速度石",
		Lv = 10,
		quality = 5,
		class = "gem",
		recycleGold = 10,
		describe = "镶嵌装备后增加60点行动速度，可在铁匠处进行相关操作",
		enchaseRate = 1,
		pickRate = 0.25,
		attr = {
			speed = 80,
		},
		areaType = "gem",
		type = "gem",
		kind = "speed",
	},
}
function GetTable()
	return autoTable
end
