--装备表
 local autoTable = {
	[151101]={
		name="短剑",
		quality=1,
		needLv=1,
		type = "weapon",
		kind = 1,
		lock=1,
		needGold=10000,
		recycleGold=240,
		describe="    由青铜所制的朴素利剑。",
		attr = {
			physcAtkMin = 214,
			physcAtkMax = 322,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		complex = 151104,
	},
	[151104]={
		name="猎魔剑",
		quality=2,
		needLv=20,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin = 406,
			physcAtkMax = 610,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155001,
		complex = 151107,
	},
	[151107]={
		name="无极剑",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin = 598,
			physcAtkMax = 898,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155002,
		complex = 151110,
	},
	[151110]={
		name="赤炎剑",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin = 790,
			physcAtkMax = 1186,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155003,
		complex = 151114,
	},
	[151114]={
		name="月影剑",
		quality=5,
		needLv=80,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin = 982,
			physcAtkMax = 1474,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155004,
		complex = 151118,
	},
	[151118]={
		name="星尘剑",
		quality=6,
		needLv=100,
		type = "weapon",
		kind = 1,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin = 1174,
			physcAtkMax = 1762,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155005,
		complex = 151122,
	},
	[151122]={
		name="玄黄破坚剑",
		quality=7,
		needLv=120,
		type = "weapon",
		kind = 1,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin = 1366,
			physcAtkMax = 2050,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155006,
	},
	[151201]={
		name="短弓",
		quality=1,
		needLv=1,
		type = "weapon",
		kind = 2,
		lock=1,
		needGold=10000,
		recycleGold=240,
		describe="    由精木制作的强力短弓。",
		attr = {
			physcAtkMin = 214,
			physcAtkMax = 322,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		complex = 151204,
	},
	[151204]={
		name="猎魔弓",
		quality=2,
		needLv=20,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcAtkMin = 406,
			physcAtkMax = 610,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155001,
		complex = 151207,
	},
	[151207]={
		name="无极弓",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcAtkMin = 598,
			physcAtkMax = 898,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155002,
		complex = 151210,
	},
	[151210]={
		name="赤炎弓",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcAtkMin = 790,
			physcAtkMax = 1186,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155003,
		complex = 151214,
	},
	[151214]={
		name="月影弓",
		quality=5,
		needLv=80,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcAtkMin = 982,
			physcAtkMax = 1474,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155004,
		complex = 151218,
	},
	[151218]={
		name="星尘弓",
		quality=6,
		needLv=100,
		type = "weapon",
		kind = 2,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcAtkMin = 1174,
			physcAtkMax = 1762,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155005,
		complex = 151222,
	},
	[151222]={
		name="玄黄破坚弓",
		quality=7,
		needLv=120,
		type = "weapon",
		kind = 2,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcAtkMin = 1366,
			physcAtkMax = 2050,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155006,
	},
	[151301]={
		name="短杖",
		quality=1,
		needLv=1,
		type = "weapon",
		kind = 3,
		lock=1,
		needGold=10000,
		recycleGold=240,
		describe="    年代久远封尘的法杖。",
		attr = {
			magicAtkMin = 154,
			magicAtkMax = 230,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		complex = 151304,
	},
	[151304]={
		name="猎魔杖",
		quality=2,
		needLv=20,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=800,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicAtkMin = 282,
			magicAtkMax = 422,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155001,
		complex = 151307,
	},
	[151307]={
		name="无极杖",
		quality=3,
		needLv=40,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=1440,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicAtkMin = 410,
			magicAtkMax = 614,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155002,
		complex = 151310,
	},
	[151310]={
		name="赤炎杖",
		quality=4,
		needLv=60,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=2400,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicAtkMin = 538,
			magicAtkMax = 806,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155003,
		complex = 151314,
	},
	[151314]={
		name="月影杖",
		quality=5,
		needLv=80,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=7360,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicAtkMin = 666,
			magicAtkMax = 998,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155004,
		complex = 151318,
	},
	[151318]={
		name="星尘杖",
		quality=6,
		needLv=100,
		type = "weapon",
		kind = 3,
		lock=2,
		recycleGold=10560,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicAtkMin = 794,
			magicAtkMax = 1190,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155005,
		complex = 151322,
	},
	[151322]={
		name="玄黄破坚杖",
		quality=7,
		needLv=120,
		type = "weapon",
		kind = 3,
		lock=1,
		recycleGold=14400,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicAtkMin = 922,
			magicAtkMax = 1382,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155006,
	},
	[151401]={
		name="麻布长袍",
		quality=1,
		needLv=1,
		type = "armor",
		kind = 4,
		lock=1,
		needGold=10000,
		recycleGold=228,
		describe="    仅供保暖的遮身长袍。",
		attr = {
			physcDef = 64,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		complex = 151404,
	},
	[151404]={
		name="猎魔袍",
		quality=2,
		needLv=20,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=760,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef = 105,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		complex = 151407,
	},
	[151407]={
		name="无极服",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=1368,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef = 158,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		complex = 151410,
	},
	[151410]={
		name="赤炎袍",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=2280,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef = 212,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		complex = 151414,
	},
	[151414]={
		name="月影袍",
		quality=5,
		needLv=80,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=6992,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef = 266,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		complex = 151418,
	},
	[151418]={
		name="星尘铠",
		quality=6,
		needLv=100,
		type = "armor",
		kind = 4,
		lock=2,
		recycleGold=10032,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef = 320,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		complex = 151422,
	},
	[151422]={
		name="玄黄破坚铠",
		quality=7,
		needLv=120,
		type = "armor",
		kind = 4,
		lock=1,
		recycleGold=13680,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef = 373,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
	},
	[151501]={
		name="兽皮护腿",
		quality=1,
		needLv=1,
		type = "armor",
		kind = 5,
		lock=1,
		needGold=10000,
		recycleGold=216,
		describe="    由猛兽的兽皮所制的护腿，具有一定的防护作用。",
		attr = {
			physcDef = 42,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		complex = 151504,
	},
	[151504]={
		name="猎魔护腿",
		quality=2,
		needLv=20,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=720,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			physcDef = 70,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		complex = 151507,
	},
	[151507]={
		name="无极护腿",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=1296,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			physcDef = 106,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		complex = 151510,
	},
	[151510]={
		name="赤炎护腿",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=2160,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			physcDef = 141,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		complex = 151514,
	},
	[151514]={
		name="月影裤",
		quality=5,
		needLv=80,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=6624,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			physcDef = 177,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		complex = 151518,
	},
	[151518]={
		name="星尘护腿",
		quality=6,
		needLv=100,
		type = "armor",
		kind = 5,
		lock=2,
		recycleGold=9504,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			physcDef = 213,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		complex = 151522,
	},
	[151522]={
		name="玄黄破坚下装",
		quality=7,
		needLv=120,
		type = "armor",
		kind = 5,
		lock=1,
		recycleGold=12960,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			physcDef = 249,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
	},
	[151601]={
		name="麻布靴",
		quality=1,
		needLv=1,
		type = "armor",
		kind = 6,
		lock=1,
		needGold=10000,
		recycleGold=192,
		describe="    麻布所制的鞋子，具有一定的防护力。",
		attr = {
			speed = 30,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		complex = 151604,
	},
	[151604]={
		name="猎魔靴",
		quality=2,
		needLv=20,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=640,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			speed = 50,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		complex = 151607,
	},
	[151607]={
		name="无极靴",
		quality=3,
		needLv=40,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=1152,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			speed = 75,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		complex = 151610,
	},
	[151610]={
		name="赤炎靴",
		quality=4,
		needLv=60,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=1920,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			speed = 101,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		complex = 151614,
	},
	[151614]={
		name="月影靴",
		quality=5,
		needLv=80,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=5888,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			speed = 126,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		complex = 151618,
	},
	[151618]={
		name="星尘靴",
		quality=6,
		needLv=100,
		type = "armor",
		kind = 6,
		lock=2,
		recycleGold=8448,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			speed = 152,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		complex = 151622,
	},
	[151622]={
		name="玄黄破坚战靴",
		quality=7,
		needLv=120,
		type = "armor",
		kind = 6,
		lock=1,
		recycleGold=11520,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			speed = 178,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
	},
	[151701]={
		name="骨制项链",
		quality=1,
		needLv=1,
		type = "jewelry",
		kind = 7,
		lock=1,
		needGold=10000,
		recycleGold=312,
		describe="    由蛮荒兽骨所制，虽然没啥用，但是也能用来辟邪的。",
		attr = {
			magicDef = 91,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		complex = 151704,
	},
	[151704]={
		name="猎魔项链",
		quality=2,
		needLv=20,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=1040,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			magicDef = 150,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		complex = 151707,
	},
	[151707]={
		name="无极项链",
		quality=3,
		needLv=40,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=1872,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			magicDef = 226,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		complex = 151710,
	},
	[151710]={
		name="赤炎项链",
		quality=4,
		needLv=60,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=3120,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			magicDef = 303,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		complex = 151714,
	},
	[151714]={
		name="月影项链",
		quality=5,
		needLv=80,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=9568,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			magicDef = 380,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		complex = 151718,
	},
	[151718]={
		name="星尘项链",
		quality=6,
		needLv=100,
		type = "jewelry",
		kind = 7,
		lock=2,
		recycleGold=13728,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			magicDef = 457,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		complex = 151722,
	},
	[151722]={
		name="玄黄破坚项链",
		quality=7,
		needLv=120,
		type = "jewelry",
		kind = 7,
		lock=1,
		recycleGold=18720,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			magicDef = 534,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
	},
	[151801]={
		name="暗淡的戒指",
		quality=1,
		needLv=1,
		type = "jewelry",
		kind = 8,
		lock=1,
		needGold=10000,
		recycleGold=288,
		describe="    不知道那里捡来的暗淡戒指。",
		attr = {
			hpMax = 464,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		complex = 151804,
	},
	[151804]={
		name="猎魔戒指",
		quality=2,
		needLv=20,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=960,
		describe="    只有真正屠过魔的人才能够获得的资格证明。",
		attr = {
			hpMax = 499,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155001,
		complex = 151807,
	},
	[151807]={
		name="无极戒指",
		quality=3,
		needLv=40,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=1728,
		describe="    无极而生，无极而灭，无极而立，无极而破。\n\t\t---是为无极。",
		attr = {
			hpMax = 755,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155002,
		complex = 151810,
	},
	[151810]={
		name="赤炎戒指",
		quality=4,
		needLv=60,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=2880,
		describe="    集天地灵气，借赤炎之火应运而生。\n\t\t---喻名赤炎。",
		attr = {
			hpMax = 1011,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155003,
		complex = 151814,
	},
	[151814]={
		name="月影戒指",
		quality=5,
		needLv=80,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=8832,
		describe="    月下起舞弄清影，如梦如幻又似真。\n\t\t---月影。",
		attr = {
			hpMax = 1267,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155004,
		complex = 151818,
	},
	[151818]={
		name="星尘戒指",
		quality=6,
		needLv=100,
		type = "jewelry",
		kind = 8,
		lock=2,
		recycleGold=12672,
		describe="    得吾厚爱的灵器哦！以吾之名赐予你名字。\n\t\t---星尘龙。",
		attr = {
			hpMax = 1523,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155005,
		complex = 151822,
	},
	[151822]={
		name="玄黄破坚戒指",
		quality=7,
		needLv=120,
		type = "jewelry",
		kind = 8,
		lock=1,
		recycleGold=17280,
		describe="    以玄黄之力造之，利无坚不摧，固无锋不抵。",
		attr = {
			hpMax = 1779,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155006,
	},
	[151830]={
		name="红莲剑",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 1,
		lock=1,
		recycleGold=10,
		describe="    红莲业火淬炼之剑，握在手中使人热血沸腾",
		attr = {
			physcAtkMin = 720,
			physcAtkMax = 1080,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
	},
	[151831]={
		name="红莲弓",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 2,
		lock=1,
		recycleGold=10,
		describe="    红莲业火淬炼之弓，握在手中使人热血沸腾",
		attr = {
			physcAtkMin = 720,
			physcAtkMax = 1080,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
	},
	[151832]={
		name="红莲杖",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 3,
		lock=1,
		recycleGold=10,
		describe="    红莲业火淬炼之杖，握在手中使人热血沸腾",
		attr = {
			magicAtkMin = 490,
			magicAtkMax = 740,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
	},
	[151833]={
		name="红莲铠",
		quality=5,
		needLv=20,
		type = "armor",
		kind = 4,
		lock=1,
		recycleGold=10,
		describe="    红莲业火淬炼之铠，冬天保暖夏天保湿的铠甲",
		attr = {
			physcDef = 190,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
	},
	[151840]={
		name="龙吟剑",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 1,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的长剑，降低了睡觉时被怪物吃掉的几率",
		attr = {
			physcAtkMin = 720,
			physcAtkMax = 1080,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="warrior",
		suitId=155007,
	},
	[151841]={
		name="龙吟弓",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 2,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的巨弓，降低了睡觉时被怪物吃掉的几率",
		attr = {
			physcAtkMin = 720,
			physcAtkMax = 1080,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="archer",
		suitId=155007,
	},
	[151842]={
		name="龙吟杖",
		quality=5,
		needLv=20,
		type = "weapon",
		kind = 3,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的法杖，降低了睡觉时被怪物吃掉的几率",
		attr = {
			magicAtkMin = 490,
			magicAtkMax = 740,
		},
		wearPos="hand",
		target="all",
		class="equip",
		areaType="equip",
		needJob="taoist",
		suitId=155007,
	},
	[151843]={
		name="龙吟战甲",
		quality=5,
		needLv=20,
		type = "armor",
		kind = 4,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的战甲，降低了睡觉时被怪物吃掉的几率",
		attr = {
			physcDef = 190,
		},
		wearPos="upperbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
	},
	[151844]={
		name="龙吟腿甲",
		quality=5,
		needLv=20,
		type = "armor",
		kind = 5,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的腿甲，降低了睡觉时被怪物吃掉的几率",
		attr = {
			physcDef = 130,
		},
		wearPos="lowerbody",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
	},
	[151845]={
		name="龙吟战靴",
		quality=5,
		needLv=20,
		type = "armor",
		kind = 6,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的战靴，降低了睡觉时被怪物吃掉的几率",
		attr = {
			speed = 90,
		},
		wearPos="foot",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
	},
	[151846]={
		name="龙吟项链",
		quality=5,
		needLv=20,
		type = "jewelry",
		kind = 7,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的项链，降低了睡觉时被怪物吃掉的几率",
		attr = {
			magicDef = 270,
		},
		wearPos="neck",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
	},
	[151847]={
		name="龙吟戒指",
		quality=5,
		needLv=20,
		type = "jewelry",
		kind = 8,
		lock=1,
		recycleGold=10,
		describe="    妖魔接近时会发出龙吟的戒指，降低了睡觉时被怪物吃掉的几率",
		attr = {
			hpMax = 910,
		},
		wearPos="finger",
		target="all",
		class="equip",
		areaType="equip",
		needJob="all",
		suitId=155007,
	},
}
function GetTable()
	return autoTable
end
