--任务列表
local autoTable = {
	["422001"] = {
		fore = "400017",
		class = "fight",
		type = "status",
		name = "仙官",
		aim = "修道是一种循环渐进的过程，如今你修为略有进步，已到下一境界的边缘。只要稍微修炼便可突破。",
		needStatusLv = 1,
		needLv = 20,
		needCopyId = 600033,
		content = "去风沙境击杀裂风虎王5次。",
		target = {
			{type = "fight", id = 230011, num = 5},
		},
		shortDesc = "去%s击杀%s",
		prize = {
			gold = 12000,
			exp = 353000,
			nimbus = 2400,
		},
		given = {
		},
		startNpcId = "210010",
		startQ = "如今你已到达了仙童的大成境界，只要稍微修炼便可突破",
		startA = "好，我这就去！",
		doingQ = "你还没去吗？",
		doingA = "我马上去。",
		endNpcId = "210010",
		endQ = "感觉如何？",
		endA = "多谢指点",
	},
	["422002"] = {
		fore = "422001",
		class = "fight",
		type = "status",
		name = "天将",
		aim = "如今你马上进入天将境界，去艰苦历练一番便能突破。",
		needStatusLv = 2,
		needLv = 30,
		needCopyId = 600070,
		content = "去婆沙森林边缘击杀利齿蜥20只",
		target = {
			{type = "fight", id = 220032, num = 20},
		},
		shortDesc = "去%s击杀%s",
		prize = {
			gold = 45000,
			exp = 555000,
			nimbus = 9000,
		},
		given = {
		},
		startNpcId = "210027",
		startQ = "看来你已经快要突破了，快去艰苦修炼一番便可突破。",
		startA = "好，我这就去！",
		doingQ = "你还没去吗？",
		doingA = "我马上去。",
		endNpcId = "210027",
		endQ = "感觉如何？",
		endA = "多谢指点",
	},
	["422003"] = {
		fore = "422002",
		class = "fight",
		type = "status",
		name = "星君",
		aim = "如今你修炼达到了一个瓶颈，需要找一个实力相当的对手对战方能参悟。",
		needStatusLv = 3,
		needLv = 40,
		needCopyId = 600098,
		content = "去战魂阁击杀战魂",
		target = {
			{type = "fight", id = 230069, num = 1},
		},
		shortDesc = "去%s击杀%s",
		prize = {
			gold = 68000,
			exp = 750000,
			nimbus = 13600,
		},
		given = {
		},
		startNpcId = "210027",
		startQ = "你需要一个对手帮助你突破。",
		startA = "好，我这就去！",
		doingQ = "你还没去吗？",
		doingA = "我马上去。",
		endNpcId = "210027",
		endQ = "感觉如何？",
		endA = "多谢指点",
	},
	["422004"] = {
		fore = "422003",
		class = "fight",
		type = "status",
		name = "正神",
		aim = "想要得偷窥天道，需要相当的实力才行。",
		needStatusLv = 4,
		needLv = 50,
		needCopyId = 600127,
		content = "去齐天塔打败熊成",
		target = {
			{type = "fight", id = 230070, num = 1},
		},
		shortDesc = "去%s打败%s",
		prize = {
			gold = 80000,
			exp = 1952000,
			nimbus = 16000,
		},
		given = {
		},
		startNpcId = "210021",
		startQ = "熊成当年也在这一境界滞留甚久，你去与他切磋定会有所感悟。",
		startA = "好，我这就去！",
		doingQ = "你还没去吗？",
		doingA = "我马上去。",
		endNpcId = "210021",
		endQ = "感觉如何？",
		endA = "多谢指点",
	},
	["422005"] = {
		fore = "422004",
		class = "fight",
		type = "status",
		name = "天君",
		aim = "修道则为逆天而行，只有破天道才能建立自己的道。",
		needStatusLv = 5,
		needLv = 60,
		needCopyId = 600128,
		content = "去齐天塔二层打败孤天",
		target = {
			{type = "fight", id = 230071, num = 1},
		},
		shortDesc = "去%s打败%s",
		prize = {
			gold = 150000,
			exp = 2810000,
			nimbus = 30000,
		},
		given = {
		},
		startNpcId = "210021",
		startQ = "修道就是逆天而行，你去齐天塔二层历练一番！",
		startA = "好，我这就去！",
		doingQ = "你还没去吗？",
		doingA = "我马上去。",
		endNpcId = "210021",
		endQ = "感觉如何？",
		endA = "多谢指点",
	},
}

function GetTable()
	return autoTable
end
