all:
	cd ./logger_service/ && $(MAKE)
	cd ./gate_service/ && $(MAKE)
	cd ./sender_service/ && $(MAKE)
	cd ./agent_service/ && $(MAKE)
	cd ./watchdog_service/ && $(MAKE)
	cd ./data_service/ && $(MAKE)
	cd ./role_service/ && $(MAKE)
	cd ./game_service/ && $(MAKE)
	cd ./center_service/ && $(MAKE)
	cd ./chores_service/ && $(MAKE)
	cd ./node_service/ && $(MAKE)
	
clean:
	cd ./logger_service/ && $(MAKE) clean
	cd ./gate_service/ && $(MAKE) clean
	cd ./sender_service/ && $(MAKE) clean
	cd ./agent_service/ && $(MAKE) clean
	cd ./watchdog_service/ && $(MAKE) clean
	cd ./data_service/ && $(MAKE) clean
	cd ./role_service/ && $(MAKE) clean
	cd ./game_service/ && $(MAKE) clean
	cd ./center_service/ && $(MAKE) clean
	cd ./chores_service/ && $(MAKE) clean
	cd ./node_service/ && $(MAKE) clean
