all:
	cd ./client/ && $(MAKE)
	cd ./data/ && $(MAKE)
	cd ./server/ && $(MAKE)
	cd ./inner/ && $(MAKE)
	cd ./config/ && $(MAKE)
	
clean:
	cd ./client/ && $(MAKE) clean
	cd ./data/  && $(MAKE) clean
	cd ./server/ && $(MAKE) clean
	cd ./inner/ && $(MAKE) clean
	cd ./config/ && $(MAKE) clean
