all:
	cd ./boss/ && $(MAKE)
	cd ./cache/ && $(MAKE)
	cd ./chat/ && $(MAKE)
	cd ./explore/ && $(MAKE)
	cd ./family/ && $(MAKE)
	cd ./friends/ && $(MAKE)
	cd ./mail/ && $(MAKE)
	cd ./raid/ && $(MAKE)
	cd ./rank/ && $(MAKE)
	cd ./team/ && $(MAKE)
	cd ./arena/ && $(MAKE)
	cd ./mate/ && $(MAKE)
	cd ./randnpc/ && $(MAKE)
	cd ./city/ && $(MAKE)
	cd ./cycle/ && $(MAKE)
	cd ./poll_activity/ && $(MAKE)
	cd ./devil/ && $(MAKE)
	cd ./illegal_word/ && $(MAKE)
	cd ./notice/ 	&& $(MAKE)
	
clean:
	cd ./boss/ && $(MAKE) clean
	cd ./cache/  && $(MAKE) clean
	cd ./chat/  && $(MAKE) clean
	cd ./explore/ && $(MAKE) clean
	cd ./family/ && $(MAKE) clean
	cd ./friends/ && $(MAKE) clean
	cd ./mail/ && $(MAKE) clean
	cd ./raid/ && $(MAKE) clean
	cd ./rank/ && $(MAKE) clean
	cd ./team/ && $(MAKE) clean
	cd ./arena/ && $(MAKE) clean
	cd ./mate/ && $(MAKE) clean
	cd ./randnpc/ && $(MAKE) clean
	cd ./city/ && $(MAKE) clean
	cd ./cycle/ && $(MAKE) clean
	cd ./poll_activity/ && $(MAKE) clean
	cd ./devil/ && $(MAKE) clean
	cd ./illegal_word/ && $(MAKE) clean
	cd ./notice/ && $(MAKE) clean
