all:
	cd ./pb/ && $(MAKE)
	cd ./base/ && $(MAKE)
	cd ./config/ && $(MAKE)
	cd ./player_role/ && $(MAKE)
	cd ./navmesh/ && $(MAKE)
	cd ./scene/ && $(MAKE)
	cd ./center/ && $(MAKE)
	cd ./chores/ && $(MAKE)
	cd ./script/ && $(MAKE)
	
clean:
	cd ./pb/ && $(MAKE) clean
	cd ./base/  && $(MAKE) clean
	cd ./config/ && $(MAKE) clean
	cd ./player_role/ && $(MAKE) clean
	cd ./navmesh/ && $(MAKE) clean
	cd ./scene/ && $(MAKE) clean
	cd ./center/ && $(MAKE) clean
	cd ./chores/ && $(MAKE) clean
	cd ./script/ && $(MAKE) clean

