// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysql.tb_role_skill.proto

#ifndef PROTOBUF_mysql_2etb_5frole_5fskill_2eproto__INCLUDED
#define PROTOBUF_mysql_2etb_5frole_5fskill_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mysql {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mysql_2etb_5frole_5fskill_2eproto();
void protobuf_AssignDesc_mysql_2etb_5frole_5fskill_2eproto();
void protobuf_ShutdownFile_mysql_2etb_5frole_5fskill_2eproto();

class tb_role_skill;

// ===================================================================

class tb_role_skill : public ::google::protobuf::Message {
 public:
  tb_role_skill();
  virtual ~tb_role_skill();

  tb_role_skill(const tb_role_skill& from);

  inline tb_role_skill& operator=(const tb_role_skill& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tb_role_skill& default_instance();

  void Swap(tb_role_skill* other);

  // implements Message ----------------------------------------------

  tb_role_skill* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tb_role_skill& from);
  void MergeFrom(const tb_role_skill& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 role_id() const;
  inline void set_role_id(::google::protobuf::uint32 value);

  // required uint32 skill_id = 2;
  inline bool has_skill_id() const;
  inline void clear_skill_id();
  static const int kSkillIdFieldNumber = 2;
  inline ::google::protobuf::uint32 skill_id() const;
  inline void set_skill_id(::google::protobuf::uint32 value);

  // required uint32 skill_level = 3;
  inline bool has_skill_level() const;
  inline void clear_skill_level();
  static const int kSkillLevelFieldNumber = 3;
  inline ::google::protobuf::uint32 skill_level() const;
  inline void set_skill_level(::google::protobuf::uint32 value);

  // required uint32 skill_grid_index = 4;
  inline bool has_skill_grid_index() const;
  inline void clear_skill_grid_index();
  static const int kSkillGridIndexFieldNumber = 4;
  inline ::google::protobuf::uint32 skill_grid_index() const;
  inline void set_skill_grid_index(::google::protobuf::uint32 value);

  // required uint32 skillful = 5;
  inline bool has_skillful() const;
  inline void clear_skillful();
  static const int kSkillfulFieldNumber = 5;
  inline ::google::protobuf::uint32 skillful() const;
  inline void set_skillful(::google::protobuf::uint32 value);

  // required uint32 studied = 6;
  inline bool has_studied() const;
  inline void clear_studied();
  static const int kStudiedFieldNumber = 6;
  inline ::google::protobuf::uint32 studied() const;
  inline void set_studied(::google::protobuf::uint32 value);

  // required uint32 end_cd_time = 7;
  inline bool has_end_cd_time() const;
  inline void clear_end_cd_time();
  static const int kEndCdTimeFieldNumber = 7;
  inline ::google::protobuf::uint32 end_cd_time() const;
  inline void set_end_cd_time(::google::protobuf::uint32 value);

  // required uint32 created_date = 8;
  inline bool has_created_date() const;
  inline void clear_created_date();
  static const int kCreatedDateFieldNumber = 8;
  inline ::google::protobuf::uint32 created_date() const;
  inline void set_created_date(::google::protobuf::uint32 value);

  // required uint32 status = 9;
  inline bool has_status() const;
  inline void clear_status();
  static const int kStatusFieldNumber = 9;
  inline ::google::protobuf::uint32 status() const;
  inline void set_status(::google::protobuf::uint32 value);

  // required uint32 effect_id = 10;
  inline bool has_effect_id() const;
  inline void clear_effect_id();
  static const int kEffectIdFieldNumber = 10;
  inline ::google::protobuf::uint32 effect_id() const;
  inline void set_effect_id(::google::protobuf::uint32 value);

  // required uint32 smy_id = 11;
  inline bool has_smy_id() const;
  inline void clear_smy_id();
  static const int kSmyIdFieldNumber = 11;
  inline ::google::protobuf::uint32 smy_id() const;
  inline void set_smy_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mysql.tb_role_skill)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_skill_id();
  inline void clear_has_skill_id();
  inline void set_has_skill_level();
  inline void clear_has_skill_level();
  inline void set_has_skill_grid_index();
  inline void clear_has_skill_grid_index();
  inline void set_has_skillful();
  inline void clear_has_skillful();
  inline void set_has_studied();
  inline void clear_has_studied();
  inline void set_has_end_cd_time();
  inline void clear_has_end_cd_time();
  inline void set_has_created_date();
  inline void clear_has_created_date();
  inline void set_has_status();
  inline void clear_has_status();
  inline void set_has_effect_id();
  inline void clear_has_effect_id();
  inline void set_has_smy_id();
  inline void clear_has_smy_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 role_id_;
  ::google::protobuf::uint32 skill_id_;
  ::google::protobuf::uint32 skill_level_;
  ::google::protobuf::uint32 skill_grid_index_;
  ::google::protobuf::uint32 skillful_;
  ::google::protobuf::uint32 studied_;
  ::google::protobuf::uint32 end_cd_time_;
  ::google::protobuf::uint32 created_date_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::uint32 effect_id_;
  ::google::protobuf::uint32 smy_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(11 + 31) / 32];

  friend void  protobuf_AddDesc_mysql_2etb_5frole_5fskill_2eproto();
  friend void protobuf_AssignDesc_mysql_2etb_5frole_5fskill_2eproto();
  friend void protobuf_ShutdownFile_mysql_2etb_5frole_5fskill_2eproto();

  void InitAsDefaultInstance();
  static tb_role_skill* default_instance_;
};
// ===================================================================


// ===================================================================

// tb_role_skill

// required uint32 role_id = 1;
inline bool tb_role_skill::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tb_role_skill::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tb_role_skill::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tb_role_skill::clear_role_id() {
  role_id_ = 0u;
  clear_has_role_id();
}
inline ::google::protobuf::uint32 tb_role_skill::role_id() const {
  return role_id_;
}
inline void tb_role_skill::set_role_id(::google::protobuf::uint32 value) {
  set_has_role_id();
  role_id_ = value;
}

// required uint32 skill_id = 2;
inline bool tb_role_skill::has_skill_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tb_role_skill::set_has_skill_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tb_role_skill::clear_has_skill_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tb_role_skill::clear_skill_id() {
  skill_id_ = 0u;
  clear_has_skill_id();
}
inline ::google::protobuf::uint32 tb_role_skill::skill_id() const {
  return skill_id_;
}
inline void tb_role_skill::set_skill_id(::google::protobuf::uint32 value) {
  set_has_skill_id();
  skill_id_ = value;
}

// required uint32 skill_level = 3;
inline bool tb_role_skill::has_skill_level() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tb_role_skill::set_has_skill_level() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tb_role_skill::clear_has_skill_level() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tb_role_skill::clear_skill_level() {
  skill_level_ = 0u;
  clear_has_skill_level();
}
inline ::google::protobuf::uint32 tb_role_skill::skill_level() const {
  return skill_level_;
}
inline void tb_role_skill::set_skill_level(::google::protobuf::uint32 value) {
  set_has_skill_level();
  skill_level_ = value;
}

// required uint32 skill_grid_index = 4;
inline bool tb_role_skill::has_skill_grid_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void tb_role_skill::set_has_skill_grid_index() {
  _has_bits_[0] |= 0x00000008u;
}
inline void tb_role_skill::clear_has_skill_grid_index() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void tb_role_skill::clear_skill_grid_index() {
  skill_grid_index_ = 0u;
  clear_has_skill_grid_index();
}
inline ::google::protobuf::uint32 tb_role_skill::skill_grid_index() const {
  return skill_grid_index_;
}
inline void tb_role_skill::set_skill_grid_index(::google::protobuf::uint32 value) {
  set_has_skill_grid_index();
  skill_grid_index_ = value;
}

// required uint32 skillful = 5;
inline bool tb_role_skill::has_skillful() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void tb_role_skill::set_has_skillful() {
  _has_bits_[0] |= 0x00000010u;
}
inline void tb_role_skill::clear_has_skillful() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void tb_role_skill::clear_skillful() {
  skillful_ = 0u;
  clear_has_skillful();
}
inline ::google::protobuf::uint32 tb_role_skill::skillful() const {
  return skillful_;
}
inline void tb_role_skill::set_skillful(::google::protobuf::uint32 value) {
  set_has_skillful();
  skillful_ = value;
}

// required uint32 studied = 6;
inline bool tb_role_skill::has_studied() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void tb_role_skill::set_has_studied() {
  _has_bits_[0] |= 0x00000020u;
}
inline void tb_role_skill::clear_has_studied() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void tb_role_skill::clear_studied() {
  studied_ = 0u;
  clear_has_studied();
}
inline ::google::protobuf::uint32 tb_role_skill::studied() const {
  return studied_;
}
inline void tb_role_skill::set_studied(::google::protobuf::uint32 value) {
  set_has_studied();
  studied_ = value;
}

// required uint32 end_cd_time = 7;
inline bool tb_role_skill::has_end_cd_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void tb_role_skill::set_has_end_cd_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void tb_role_skill::clear_has_end_cd_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void tb_role_skill::clear_end_cd_time() {
  end_cd_time_ = 0u;
  clear_has_end_cd_time();
}
inline ::google::protobuf::uint32 tb_role_skill::end_cd_time() const {
  return end_cd_time_;
}
inline void tb_role_skill::set_end_cd_time(::google::protobuf::uint32 value) {
  set_has_end_cd_time();
  end_cd_time_ = value;
}

// required uint32 created_date = 8;
inline bool tb_role_skill::has_created_date() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void tb_role_skill::set_has_created_date() {
  _has_bits_[0] |= 0x00000080u;
}
inline void tb_role_skill::clear_has_created_date() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void tb_role_skill::clear_created_date() {
  created_date_ = 0u;
  clear_has_created_date();
}
inline ::google::protobuf::uint32 tb_role_skill::created_date() const {
  return created_date_;
}
inline void tb_role_skill::set_created_date(::google::protobuf::uint32 value) {
  set_has_created_date();
  created_date_ = value;
}

// required uint32 status = 9;
inline bool tb_role_skill::has_status() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void tb_role_skill::set_has_status() {
  _has_bits_[0] |= 0x00000100u;
}
inline void tb_role_skill::clear_has_status() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void tb_role_skill::clear_status() {
  status_ = 0u;
  clear_has_status();
}
inline ::google::protobuf::uint32 tb_role_skill::status() const {
  return status_;
}
inline void tb_role_skill::set_status(::google::protobuf::uint32 value) {
  set_has_status();
  status_ = value;
}

// required uint32 effect_id = 10;
inline bool tb_role_skill::has_effect_id() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void tb_role_skill::set_has_effect_id() {
  _has_bits_[0] |= 0x00000200u;
}
inline void tb_role_skill::clear_has_effect_id() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void tb_role_skill::clear_effect_id() {
  effect_id_ = 0u;
  clear_has_effect_id();
}
inline ::google::protobuf::uint32 tb_role_skill::effect_id() const {
  return effect_id_;
}
inline void tb_role_skill::set_effect_id(::google::protobuf::uint32 value) {
  set_has_effect_id();
  effect_id_ = value;
}

// required uint32 smy_id = 11;
inline bool tb_role_skill::has_smy_id() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void tb_role_skill::set_has_smy_id() {
  _has_bits_[0] |= 0x00000400u;
}
inline void tb_role_skill::clear_has_smy_id() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void tb_role_skill::clear_smy_id() {
  smy_id_ = 0u;
  clear_has_smy_id();
}
inline ::google::protobuf::uint32 tb_role_skill::smy_id() const {
  return smy_id_;
}
inline void tb_role_skill::set_smy_id(::google::protobuf::uint32 value) {
  set_has_smy_id();
  smy_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mysql

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mysql_2etb_5frole_5fskill_2eproto__INCLUDED
