// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysql.tb_role_friends.proto

#ifndef PROTOBUF_mysql_2etb_5frole_5ffriends_2eproto__INCLUDED
#define PROTOBUF_mysql_2etb_5frole_5ffriends_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mysql {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mysql_2etb_5frole_5ffriends_2eproto();
void protobuf_AssignDesc_mysql_2etb_5frole_5ffriends_2eproto();
void protobuf_ShutdownFile_mysql_2etb_5frole_5ffriends_2eproto();

class tb_role_friends;

// ===================================================================

class tb_role_friends : public ::google::protobuf::Message {
 public:
  tb_role_friends();
  virtual ~tb_role_friends();

  tb_role_friends(const tb_role_friends& from);

  inline tb_role_friends& operator=(const tb_role_friends& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tb_role_friends& default_instance();

  void Swap(tb_role_friends* other);

  // implements Message ----------------------------------------------

  tb_role_friends* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tb_role_friends& from);
  void MergeFrom(const tb_role_friends& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 role_id() const;
  inline void set_role_id(::google::protobuf::uint32 value);

  // required bytes friends = 2;
  inline bool has_friends() const;
  inline void clear_friends();
  static const int kFriendsFieldNumber = 2;
  inline const ::std::string& friends() const;
  inline void set_friends(const ::std::string& value);
  inline void set_friends(const char* value);
  inline void set_friends(const void* value, size_t size);
  inline ::std::string* mutable_friends();
  inline ::std::string* release_friends();
  inline void set_allocated_friends(::std::string* friends);

  // @@protoc_insertion_point(class_scope:mysql.tb_role_friends)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_friends();
  inline void clear_has_friends();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* friends_;
  ::google::protobuf::uint32 role_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_mysql_2etb_5frole_5ffriends_2eproto();
  friend void protobuf_AssignDesc_mysql_2etb_5frole_5ffriends_2eproto();
  friend void protobuf_ShutdownFile_mysql_2etb_5frole_5ffriends_2eproto();

  void InitAsDefaultInstance();
  static tb_role_friends* default_instance_;
};
// ===================================================================


// ===================================================================

// tb_role_friends

// required uint32 role_id = 1;
inline bool tb_role_friends::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tb_role_friends::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tb_role_friends::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tb_role_friends::clear_role_id() {
  role_id_ = 0u;
  clear_has_role_id();
}
inline ::google::protobuf::uint32 tb_role_friends::role_id() const {
  return role_id_;
}
inline void tb_role_friends::set_role_id(::google::protobuf::uint32 value) {
  set_has_role_id();
  role_id_ = value;
}

// required bytes friends = 2;
inline bool tb_role_friends::has_friends() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tb_role_friends::set_has_friends() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tb_role_friends::clear_has_friends() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tb_role_friends::clear_friends() {
  if (friends_ != &::google::protobuf::internal::kEmptyString) {
    friends_->clear();
  }
  clear_has_friends();
}
inline const ::std::string& tb_role_friends::friends() const {
  return *friends_;
}
inline void tb_role_friends::set_friends(const ::std::string& value) {
  set_has_friends();
  if (friends_ == &::google::protobuf::internal::kEmptyString) {
    friends_ = new ::std::string;
  }
  friends_->assign(value);
}
inline void tb_role_friends::set_friends(const char* value) {
  set_has_friends();
  if (friends_ == &::google::protobuf::internal::kEmptyString) {
    friends_ = new ::std::string;
  }
  friends_->assign(value);
}
inline void tb_role_friends::set_friends(const void* value, size_t size) {
  set_has_friends();
  if (friends_ == &::google::protobuf::internal::kEmptyString) {
    friends_ = new ::std::string;
  }
  friends_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* tb_role_friends::mutable_friends() {
  set_has_friends();
  if (friends_ == &::google::protobuf::internal::kEmptyString) {
    friends_ = new ::std::string;
  }
  return friends_;
}
inline ::std::string* tb_role_friends::release_friends() {
  clear_has_friends();
  if (friends_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = friends_;
    friends_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void tb_role_friends::set_allocated_friends(::std::string* friends) {
  if (friends_ != &::google::protobuf::internal::kEmptyString) {
    delete friends_;
  }
  if (friends) {
    set_has_friends();
    friends_ = friends;
  } else {
    clear_has_friends();
    friends_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mysql

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mysql_2etb_5frole_5ffriends_2eproto__INCLUDED
