// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysql.tb_role_center_set.proto

#ifndef PROTOBUF_mysql_2etb_5frole_5fcenter_5fset_2eproto__INCLUDED
#define PROTOBUF_mysql_2etb_5frole_5fcenter_5fset_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mysql {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mysql_2etb_5frole_5fcenter_5fset_2eproto();
void protobuf_AssignDesc_mysql_2etb_5frole_5fcenter_5fset_2eproto();
void protobuf_ShutdownFile_mysql_2etb_5frole_5fcenter_5fset_2eproto();

class tb_role_center_set;

// ===================================================================

class tb_role_center_set : public ::google::protobuf::Message {
 public:
  tb_role_center_set();
  virtual ~tb_role_center_set();

  tb_role_center_set(const tb_role_center_set& from);

  inline tb_role_center_set& operator=(const tb_role_center_set& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tb_role_center_set& default_instance();

  void Swap(tb_role_center_set* other);

  // implements Message ----------------------------------------------

  tb_role_center_set* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tb_role_center_set& from);
  void MergeFrom(const tb_role_center_set& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 role_id() const;
  inline void set_role_id(::google::protobuf::uint32 value);

  // required uint32 team_auto_agree = 2;
  inline bool has_team_auto_agree() const;
  inline void clear_team_auto_agree();
  static const int kTeamAutoAgreeFieldNumber = 2;
  inline ::google::protobuf::uint32 team_auto_agree() const;
  inline void set_team_auto_agree(::google::protobuf::uint32 value);

  // required uint32 team_auto_join = 3;
  inline bool has_team_auto_join() const;
  inline void clear_team_auto_join();
  static const int kTeamAutoJoinFieldNumber = 3;
  inline ::google::protobuf::uint32 team_auto_join() const;
  inline void set_team_auto_join(::google::protobuf::uint32 value);

  // required uint32 team_min_lvl = 4;
  inline bool has_team_min_lvl() const;
  inline void clear_team_min_lvl();
  static const int kTeamMinLvlFieldNumber = 4;
  inline ::google::protobuf::uint32 team_min_lvl() const;
  inline void set_team_min_lvl(::google::protobuf::uint32 value);

  // required uint32 team_max_lvl = 5;
  inline bool has_team_max_lvl() const;
  inline void clear_team_max_lvl();
  static const int kTeamMaxLvlFieldNumber = 5;
  inline ::google::protobuf::uint32 team_max_lvl() const;
  inline void set_team_max_lvl(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mysql.tb_role_center_set)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_team_auto_agree();
  inline void clear_has_team_auto_agree();
  inline void set_has_team_auto_join();
  inline void clear_has_team_auto_join();
  inline void set_has_team_min_lvl();
  inline void clear_has_team_min_lvl();
  inline void set_has_team_max_lvl();
  inline void clear_has_team_max_lvl();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 role_id_;
  ::google::protobuf::uint32 team_auto_agree_;
  ::google::protobuf::uint32 team_auto_join_;
  ::google::protobuf::uint32 team_min_lvl_;
  ::google::protobuf::uint32 team_max_lvl_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_mysql_2etb_5frole_5fcenter_5fset_2eproto();
  friend void protobuf_AssignDesc_mysql_2etb_5frole_5fcenter_5fset_2eproto();
  friend void protobuf_ShutdownFile_mysql_2etb_5frole_5fcenter_5fset_2eproto();

  void InitAsDefaultInstance();
  static tb_role_center_set* default_instance_;
};
// ===================================================================


// ===================================================================

// tb_role_center_set

// required uint32 role_id = 1;
inline bool tb_role_center_set::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tb_role_center_set::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tb_role_center_set::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tb_role_center_set::clear_role_id() {
  role_id_ = 0u;
  clear_has_role_id();
}
inline ::google::protobuf::uint32 tb_role_center_set::role_id() const {
  return role_id_;
}
inline void tb_role_center_set::set_role_id(::google::protobuf::uint32 value) {
  set_has_role_id();
  role_id_ = value;
}

// required uint32 team_auto_agree = 2;
inline bool tb_role_center_set::has_team_auto_agree() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tb_role_center_set::set_has_team_auto_agree() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tb_role_center_set::clear_has_team_auto_agree() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tb_role_center_set::clear_team_auto_agree() {
  team_auto_agree_ = 0u;
  clear_has_team_auto_agree();
}
inline ::google::protobuf::uint32 tb_role_center_set::team_auto_agree() const {
  return team_auto_agree_;
}
inline void tb_role_center_set::set_team_auto_agree(::google::protobuf::uint32 value) {
  set_has_team_auto_agree();
  team_auto_agree_ = value;
}

// required uint32 team_auto_join = 3;
inline bool tb_role_center_set::has_team_auto_join() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tb_role_center_set::set_has_team_auto_join() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tb_role_center_set::clear_has_team_auto_join() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tb_role_center_set::clear_team_auto_join() {
  team_auto_join_ = 0u;
  clear_has_team_auto_join();
}
inline ::google::protobuf::uint32 tb_role_center_set::team_auto_join() const {
  return team_auto_join_;
}
inline void tb_role_center_set::set_team_auto_join(::google::protobuf::uint32 value) {
  set_has_team_auto_join();
  team_auto_join_ = value;
}

// required uint32 team_min_lvl = 4;
inline bool tb_role_center_set::has_team_min_lvl() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void tb_role_center_set::set_has_team_min_lvl() {
  _has_bits_[0] |= 0x00000008u;
}
inline void tb_role_center_set::clear_has_team_min_lvl() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void tb_role_center_set::clear_team_min_lvl() {
  team_min_lvl_ = 0u;
  clear_has_team_min_lvl();
}
inline ::google::protobuf::uint32 tb_role_center_set::team_min_lvl() const {
  return team_min_lvl_;
}
inline void tb_role_center_set::set_team_min_lvl(::google::protobuf::uint32 value) {
  set_has_team_min_lvl();
  team_min_lvl_ = value;
}

// required uint32 team_max_lvl = 5;
inline bool tb_role_center_set::has_team_max_lvl() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void tb_role_center_set::set_has_team_max_lvl() {
  _has_bits_[0] |= 0x00000010u;
}
inline void tb_role_center_set::clear_has_team_max_lvl() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void tb_role_center_set::clear_team_max_lvl() {
  team_max_lvl_ = 0u;
  clear_has_team_max_lvl();
}
inline ::google::protobuf::uint32 tb_role_center_set::team_max_lvl() const {
  return team_max_lvl_;
}
inline void tb_role_center_set::set_team_max_lvl(::google::protobuf::uint32 value) {
  set_has_team_max_lvl();
  team_max_lvl_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mysql

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mysql_2etb_5frole_5fcenter_5fset_2eproto__INCLUDED
