// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysql.tb_role_explore_detail.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mysql.tb_role_explore_detail.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mysql {

namespace {

const ::google::protobuf::Descriptor* tb_role_explore_detail_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  tb_role_explore_detail_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto() {
  protobuf_AddDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mysql.tb_role_explore_detail.proto");
  GOOGLE_CHECK(file != NULL);
  tb_role_explore_detail_descriptor_ = file->message_type(0);
  static const int tb_role_explore_detail_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, role_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, place_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, goods_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, goods_num_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, goods_quality_),
  };
  tb_role_explore_detail_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      tb_role_explore_detail_descriptor_,
      tb_role_explore_detail::default_instance_,
      tb_role_explore_detail_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(tb_role_explore_detail, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(tb_role_explore_detail));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    tb_role_explore_detail_descriptor_, &tb_role_explore_detail::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mysql_2etb_5frole_5fexplore_5fdetail_2eproto() {
  delete tb_role_explore_detail::default_instance_;
  delete tb_role_explore_detail_reflection_;
}

void protobuf_AddDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"mysql.tb_role_explore_detail.proto\022\005my"
    "sql\"\221\001\n\026tb_role_explore_detail\022\n\n\002id\030\001 \002"
    "(\r\022\017\n\007role_id\030\002 \002(\r\022\014\n\004time\030\003 \002(\r\022\020\n\010pla"
    "ce_id\030\004 \002(\r\022\020\n\010goods_id\030\005 \002(\r\022\021\n\tgoods_n"
    "um\030\006 \002(\r\022\025\n\rgoods_quality\030\007 \002(\r", 191);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mysql.tb_role_explore_detail.proto", &protobuf_RegisterTypes);
  tb_role_explore_detail::default_instance_ = new tb_role_explore_detail();
  tb_role_explore_detail::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mysql_2etb_5frole_5fexplore_5fdetail_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mysql_2etb_5frole_5fexplore_5fdetail_2eproto {
  StaticDescriptorInitializer_mysql_2etb_5frole_5fexplore_5fdetail_2eproto() {
    protobuf_AddDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto();
  }
} static_descriptor_initializer_mysql_2etb_5frole_5fexplore_5fdetail_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int tb_role_explore_detail::kIdFieldNumber;
const int tb_role_explore_detail::kRoleIdFieldNumber;
const int tb_role_explore_detail::kTimeFieldNumber;
const int tb_role_explore_detail::kPlaceIdFieldNumber;
const int tb_role_explore_detail::kGoodsIdFieldNumber;
const int tb_role_explore_detail::kGoodsNumFieldNumber;
const int tb_role_explore_detail::kGoodsQualityFieldNumber;
#endif  // !_MSC_VER

tb_role_explore_detail::tb_role_explore_detail()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void tb_role_explore_detail::InitAsDefaultInstance() {
}

tb_role_explore_detail::tb_role_explore_detail(const tb_role_explore_detail& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void tb_role_explore_detail::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  role_id_ = 0u;
  time_ = 0u;
  place_id_ = 0u;
  goods_id_ = 0u;
  goods_num_ = 0u;
  goods_quality_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

tb_role_explore_detail::~tb_role_explore_detail() {
  SharedDtor();
}

void tb_role_explore_detail::SharedDtor() {
  if (this != default_instance_) {
  }
}

void tb_role_explore_detail::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tb_role_explore_detail::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return tb_role_explore_detail_descriptor_;
}

const tb_role_explore_detail& tb_role_explore_detail::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mysql_2etb_5frole_5fexplore_5fdetail_2eproto();
  return *default_instance_;
}

tb_role_explore_detail* tb_role_explore_detail::default_instance_ = NULL;

tb_role_explore_detail* tb_role_explore_detail::New() const {
  return new tb_role_explore_detail;
}

void tb_role_explore_detail::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    role_id_ = 0u;
    time_ = 0u;
    place_id_ = 0u;
    goods_id_ = 0u;
    goods_num_ = 0u;
    goods_quality_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool tb_role_explore_detail::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_role_id;
        break;
      }

      // required uint32 role_id = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_role_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &role_id_)));
          set_has_role_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_time;
        break;
      }

      // required uint32 time = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_place_id;
        break;
      }

      // required uint32 place_id = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_place_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &place_id_)));
          set_has_place_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_goods_id;
        break;
      }

      // required uint32 goods_id = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_goods_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &goods_id_)));
          set_has_goods_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_goods_num;
        break;
      }

      // required uint32 goods_num = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_goods_num:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &goods_num_)));
          set_has_goods_num();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_goods_quality;
        break;
      }

      // required uint32 goods_quality = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_goods_quality:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &goods_quality_)));
          set_has_goods_quality();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void tb_role_explore_detail::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required uint32 role_id = 2;
  if (has_role_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->role_id(), output);
  }

  // required uint32 time = 3;
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->time(), output);
  }

  // required uint32 place_id = 4;
  if (has_place_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->place_id(), output);
  }

  // required uint32 goods_id = 5;
  if (has_goods_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->goods_id(), output);
  }

  // required uint32 goods_num = 6;
  if (has_goods_num()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->goods_num(), output);
  }

  // required uint32 goods_quality = 7;
  if (has_goods_quality()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->goods_quality(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* tb_role_explore_detail::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required uint32 role_id = 2;
  if (has_role_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->role_id(), target);
  }

  // required uint32 time = 3;
  if (has_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->time(), target);
  }

  // required uint32 place_id = 4;
  if (has_place_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->place_id(), target);
  }

  // required uint32 goods_id = 5;
  if (has_goods_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->goods_id(), target);
  }

  // required uint32 goods_num = 6;
  if (has_goods_num()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->goods_num(), target);
  }

  // required uint32 goods_quality = 7;
  if (has_goods_quality()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->goods_quality(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int tb_role_explore_detail::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // required uint32 role_id = 2;
    if (has_role_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->role_id());
    }

    // required uint32 time = 3;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->time());
    }

    // required uint32 place_id = 4;
    if (has_place_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->place_id());
    }

    // required uint32 goods_id = 5;
    if (has_goods_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->goods_id());
    }

    // required uint32 goods_num = 6;
    if (has_goods_num()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->goods_num());
    }

    // required uint32 goods_quality = 7;
    if (has_goods_quality()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->goods_quality());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tb_role_explore_detail::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const tb_role_explore_detail* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const tb_role_explore_detail*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void tb_role_explore_detail::MergeFrom(const tb_role_explore_detail& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_role_id()) {
      set_role_id(from.role_id());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_place_id()) {
      set_place_id(from.place_id());
    }
    if (from.has_goods_id()) {
      set_goods_id(from.goods_id());
    }
    if (from.has_goods_num()) {
      set_goods_num(from.goods_num());
    }
    if (from.has_goods_quality()) {
      set_goods_quality(from.goods_quality());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void tb_role_explore_detail::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tb_role_explore_detail::CopyFrom(const tb_role_explore_detail& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tb_role_explore_detail::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  return true;
}

void tb_role_explore_detail::Swap(tb_role_explore_detail* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(role_id_, other->role_id_);
    std::swap(time_, other->time_);
    std::swap(place_id_, other->place_id_);
    std::swap(goods_id_, other->goods_id_);
    std::swap(goods_num_, other->goods_num_);
    std::swap(goods_quality_, other->goods_quality_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata tb_role_explore_detail::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = tb_role_explore_detail_descriptor_;
  metadata.reflection = tb_role_explore_detail_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mysql

// @@protoc_insertion_point(global_scope)
