// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mysql.tb_role_explore.proto

#ifndef PROTOBUF_mysql_2etb_5frole_5fexplore_2eproto__INCLUDED
#define PROTOBUF_mysql_2etb_5frole_5fexplore_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mysql {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mysql_2etb_5frole_5fexplore_2eproto();
void protobuf_AssignDesc_mysql_2etb_5frole_5fexplore_2eproto();
void protobuf_ShutdownFile_mysql_2etb_5frole_5fexplore_2eproto();

class tb_role_explore;

// ===================================================================

class tb_role_explore : public ::google::protobuf::Message {
 public:
  tb_role_explore();
  virtual ~tb_role_explore();

  tb_role_explore(const tb_role_explore& from);

  inline tb_role_explore& operator=(const tb_role_explore& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const tb_role_explore& default_instance();

  void Swap(tb_role_explore* other);

  // implements Message ----------------------------------------------

  tb_role_explore* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const tb_role_explore& from);
  void MergeFrom(const tb_role_explore& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint32 role_id() const;
  inline void set_role_id(::google::protobuf::uint32 value);

  // required uint32 num = 2;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 2;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // required uint32 money = 3;
  inline bool has_money() const;
  inline void clear_money();
  static const int kMoneyFieldNumber = 3;
  inline ::google::protobuf::uint32 money() const;
  inline void set_money(::google::protobuf::uint32 value);

  // required uint32 success_ratio = 4;
  inline bool has_success_ratio() const;
  inline void clear_success_ratio();
  static const int kSuccessRatioFieldNumber = 4;
  inline ::google::protobuf::uint32 success_ratio() const;
  inline void set_success_ratio(::google::protobuf::uint32 value);

  // required uint32 failure_money = 5;
  inline bool has_failure_money() const;
  inline void clear_failure_money();
  static const int kFailureMoneyFieldNumber = 5;
  inline ::google::protobuf::uint32 failure_money() const;
  inline void set_failure_money(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mysql.tb_role_explore)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_num();
  inline void clear_has_num();
  inline void set_has_money();
  inline void clear_has_money();
  inline void set_has_success_ratio();
  inline void clear_has_success_ratio();
  inline void set_has_failure_money();
  inline void clear_has_failure_money();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 role_id_;
  ::google::protobuf::uint32 num_;
  ::google::protobuf::uint32 money_;
  ::google::protobuf::uint32 success_ratio_;
  ::google::protobuf::uint32 failure_money_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_mysql_2etb_5frole_5fexplore_2eproto();
  friend void protobuf_AssignDesc_mysql_2etb_5frole_5fexplore_2eproto();
  friend void protobuf_ShutdownFile_mysql_2etb_5frole_5fexplore_2eproto();

  void InitAsDefaultInstance();
  static tb_role_explore* default_instance_;
};
// ===================================================================


// ===================================================================

// tb_role_explore

// required uint32 role_id = 1;
inline bool tb_role_explore::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void tb_role_explore::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void tb_role_explore::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void tb_role_explore::clear_role_id() {
  role_id_ = 0u;
  clear_has_role_id();
}
inline ::google::protobuf::uint32 tb_role_explore::role_id() const {
  return role_id_;
}
inline void tb_role_explore::set_role_id(::google::protobuf::uint32 value) {
  set_has_role_id();
  role_id_ = value;
}

// required uint32 num = 2;
inline bool tb_role_explore::has_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void tb_role_explore::set_has_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void tb_role_explore::clear_has_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void tb_role_explore::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 tb_role_explore::num() const {
  return num_;
}
inline void tb_role_explore::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// required uint32 money = 3;
inline bool tb_role_explore::has_money() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void tb_role_explore::set_has_money() {
  _has_bits_[0] |= 0x00000004u;
}
inline void tb_role_explore::clear_has_money() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void tb_role_explore::clear_money() {
  money_ = 0u;
  clear_has_money();
}
inline ::google::protobuf::uint32 tb_role_explore::money() const {
  return money_;
}
inline void tb_role_explore::set_money(::google::protobuf::uint32 value) {
  set_has_money();
  money_ = value;
}

// required uint32 success_ratio = 4;
inline bool tb_role_explore::has_success_ratio() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void tb_role_explore::set_has_success_ratio() {
  _has_bits_[0] |= 0x00000008u;
}
inline void tb_role_explore::clear_has_success_ratio() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void tb_role_explore::clear_success_ratio() {
  success_ratio_ = 0u;
  clear_has_success_ratio();
}
inline ::google::protobuf::uint32 tb_role_explore::success_ratio() const {
  return success_ratio_;
}
inline void tb_role_explore::set_success_ratio(::google::protobuf::uint32 value) {
  set_has_success_ratio();
  success_ratio_ = value;
}

// required uint32 failure_money = 5;
inline bool tb_role_explore::has_failure_money() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void tb_role_explore::set_has_failure_money() {
  _has_bits_[0] |= 0x00000010u;
}
inline void tb_role_explore::clear_has_failure_money() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void tb_role_explore::clear_failure_money() {
  failure_money_ = 0u;
  clear_has_failure_money();
}
inline ::google::protobuf::uint32 tb_role_explore::failure_money() const {
  return failure_money_;
}
inline void tb_role_explore::set_failure_money(::google::protobuf::uint32 value) {
  set_has_failure_money();
  failure_money_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace mysql

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mysql_2etb_5frole_5fexplore_2eproto__INCLUDED
